### ISSUE TITLE
Rampant Java Wakeups before resulting hang on OS Sierra 

### ISSUE THREAD

**Issue by Swampgirl** [BiglySoftware/BiglyBT#1033] opened 2019-04-28 16:33 UTC
Not my dreams, but In my nightmares, parg. This happens whenever I have an extra window open, or try to do more than one thing in BiglyBT. Plus, if I have a list of downloads - more than 2 or 3, I get memory warnings, immediately. So if I have 15 things queued to download (in stopped state), and am downloading 2 or 3 of them at a time, I receive memory warnings until the program hangs, then crashes.

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro9,2
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
  Boot ROM Version:	224.0.0.0.0
  SMC Version (system):	2.2f44

 System Software Version: 	macOS 10.12.6 (16G1918)
  Kernel Version:	Darwin 16.7.0

BiglyBTBeta Version: 1.9.0.1_B14

Java Version: 1.8.0_221

**From Console:**
Date/Time:       2019-04-28 09:50:56.881465 -0400
OS Version:      Mac OS X 10.12.6 (Build 16G1918)
Architecture:    x86_64
Report Version:  19

Command:         JavaApplicationStub
Path:            /Applications/BiglyBT/BiglyBT.app/Contents/MacOS/JavaApplicationStub
Version:         1.9.0.0 (1.9.0.0)
Parent:          launchd [1]
PID:             8448

**Event:           wakeups**
**Wakeups:         45003 wakeups over the last 135 seconds (334 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds**
Duration:        134.75s
Steps:           114

Hardware model:  MacBookPro9,2
Active cpus:     4

**Fan speed:       2000 rpm**

Powerstats for:  JavaApplicationS [8448]
UUID:            BDCF65D5-287B-3C3D-BA73-C66AA356CB41
Start time:      2019-04-28 09:50:57 -0400
End time:        2019-04-28 09:53:10 -0400
Microstackshots: 114 samples (100%)
Primary state:   61 samples Frontmost App, User mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Unspecified
User Activity:   0 samples Idle, 114 samples Active
Power Source:    0 samples on Battery, 114 samples on AC
  81  thread_start + 13 (libsystem_pthread.dylib) [0x7fffa5ab308d]
    81  _pthread_start + 286 (libsystem_pthread.dylib) [0x7fffa5ab3887]
      81  _pthread_body + 180 (libsystem_pthread.dylib) [0x7fffa5ab393b]
        81  java_start(Thread*) + 246 (libjvm.dylib) [0x103d4830a]
          79  JavaThread::run() + 450 (libjvm.dylib) [0x103e2b28e]
            79  JavaThread::thread_main_inner() + 155 (libjvm.dylib) [0x103e29b93]
              48  thread_entry(JavaThread*, Thread*) + 124 (libjvm.dylib) [0x103c04f5d]
                48  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*) + 74 (libjvm.dylib) [0x103baa66e]
                  48  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*) + 356 (libjvm.dylib) [0x103baa4c2]
                    48  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) + 1710 (libjvm.dylib) [0x103ba9d1e]
                      48  ??? [0x109def7a7]
                        39  ??? [0x109df72bd]
                          19  ??? [0x109df7302]
                            12  ??? [0x109df72bd]
                              5   ??? [0x109df72bd]
                                3   ??? [0x109df7040]
                                  3   ??? [0x109df7040]
                                    3   ??? [0x109df7040]
                                      3   ??? [0x109df7040]
                                        3   ??? [0x109df7040]
                                          3   ??? [0x109df7040]
                                            3   ??? [0x109df7040]
                                              3   ??? [0x109df7040]
                                                3   ??? [0x109df7040]
                                                  2   ??? [0x109df7040]
                                                    2   ??? [0x10ace3fec]
                                                      2   ??? [0x10a2872ed]
                                                        2   Java_net_i2p_util_NativeBigInteger_nativeModPow + 100 

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment] 2019-04-28 16:42
What is the JVM heap size listed towards the bottom of Tools->Options->Startup & Shutdown? 

Also can you look in the logs folder (location can be found by clicking on the 'user-specific plugins directory' link near the top of Tools->Options->Plugins and then navigating up one folder) for files named Thread_1.log and Thread_2.log and upload them?

**Comment by Swampgirl** [comment] 2019-05-04 16:28
I apologize for not responding sooner. Thank you for getting back to me. Here are the things you requested:
![BBT Starup   Shutdown Screen Shot 2019-05-04 at 11 28 21 AM](https://user-images.githubusercontent.com/24909475/57181963-01f50600-6e68-11e9-842c-3f197fc1de63.png)

[thread_1.log](https://github.com/BiglySoftware/BiglyBT/files/3144572/thread_1.log)

[thread_2.log](https://github.com/BiglySoftware/BiglyBT/files/3144573/thread_2.log)
 **And didn't request:

![Console view of BBT Java-related issues](https://user-images.githubusercontent.com/24909475/57181973-205b0180-6e68-11e9-96b6-cda22e35a996.png)

**Comment by parg** [comment] 2019-05-04 19:31
Hmm, nothing there that's points to anything :( If you're not actively using I2P then you could try disabling the 'I2P Helper Plugin' under Tools->Options->Plugins to see if that helps.

**Comment by Swampgirl** [comment] 2019-05-05 17:01
Thank You Parg. The i2P plugin was one I left in after getting rid of many. I will disable the plugin. All the Java hangs etc. from the Console Screenshot above are all generated by BiglyBT. One consistent issue (in that it happens now _every_ time since I updated the BBT app), is that when I open a chat window, e.g. Help, I can only type a few words before Java hangs, the software freezes, and then is unresponsive, requiring me to shut down the app and restart. I am going to double check that Java Home is configured correctly. 

Further, I went through all the old info regarding how to reduce memory again, because BiglyBt seems to be going through memory like a buzzsaw. I get memory alerts while it is downloading even just 1 torrent, until the app freezes. Until about 2 or 3 months ago, when all the crashing started, I used to be able to leave the app running during the night. This is no longer possible. Even with one download, the memory maxes out, and the software will remain in a crashed state all night, until I find it and reboot it in the morning.

Conversely, while this behavior happens nearly 90% of the time, occasionally, 3-4 torrents will quickly download with no memory warnings, fans beginning to whirr, or Java hangs. I am at a loss. I have done all the little tricks I learned over the past 15 years, and nothing is working.

If I wanted to install a brand new copy of BiglyBT, is there a way I can keep my subscriptions and trackers, and then import them after I do a new install? I am concerned that if I just reload a backup configuration, it will just bring the old problems back, however, I do not want to lose the subscriptions (subs? - usually in listed in sidebar from which I generate torrent downloads), nor the trackers. I will if I have to, but I really do not want to.

Another question I have had about Java, is whether I need more than the most recent updated version of Java for Mac OS Sierra running 
BiglyBT. This question comes from old blogs (Vuze), and the Java site itself. And while I am here, how do I properly configure Java for BiglyBT (i.e., place in HOME path)?  By asking you, I am making sure that what I am doing is correct. 

Also, I've read in chats that you maintain "programming is so easy that....". I do understand the context in which the statement was made, and did not take it personally. However, I do not know where to start. I can do basic things I have googled, carefully described and outlined, but just off the cuff? Well, no, I have no idea. Where to start? I figure most problems out by going to stackoverflow.com. I am comfortable with working on the command line, etc., but I do not know how to go in and change stuff that is driving me crazy, like the download icon, or how to place the Java executable in the HOME path without looking it up again. So I am teachable, but I do not really learn how to program from problem solving. And I am "legal." ;)

Right now my software is nearly unusable. I'm just trying to figure out why. 

And finally, recently you gave me advice regarding creating a download "Tag" in a chat. I'm not sure what that Tag was meant to accomplish. But here is the reason I want to try to reinstall Bigly BT, without a backup configuration. Once torrents finish downloading, the Download icon disappears. It does not reappear if I select new torrents to download. I have to go into Options>Display each time, then unselect then select "Display Downloads," for the Download icon to reappear - Tag or no. If I reboot the software, sometimes the selection of "Display Downloads" is unchecked and I have to re-check it OR it remains checked, and I have to uncheck it, then check it again, for the icon to appear. 
Moreover, if one download remains in a stopped state, when I reboot (which lately is often), the download icon disappears, and must again be unchecked and reselected. And forgive the repetition, but a download can be in a stopped state, the software rebooted, and the "Display Download" selection will be unchecked, and the icon of course missing from the sidebar.

This _never_ happened when I used Vuze. This is not a complaint about BiglyBT - it is only an observation. The download icon was always static (I have been on both Macs and PCs, mostly Macs with the Azureus-based software. I never had to choose it, much less make sure it was selected in the Display configuration in Options. It was never an issue. I do not understand why this cannot be a static category like the "New" Category, which remains in my sidebar no matter what.

I let this issue go when I was reluctant to do a clean install of the software because I did not want to go through the hassle of reconstructing a subscription menu, and re-collect various trackers. However, when I finally did reinstall a new version of BiglyBt, I have had these non-stop Java hangs/crashes, and the Download icon issue was not resolved.  I figured that the reason the Download icon would not remain showing, or reappear when there were new torrents to download, was that somehow my Java preferences were dictating the behavior, or that it was an old glitch in the software. 

However, you said you thought you fixed it. I am at a loss as to how to get back that one aspect of the software configuration - that apparently remains important enough to me for me to go into the software every time the Download icon disappears, which is everyday, several times, and reselect it. So I am, once again seeing if there is something you can do. I wonder if it only affects Macs, or is a bug I am somehow carrying from one software version to the next, despite clean installs. I just don't know. This is why I would love to know how to program the software to make that damned icon static.

The other thing I am sure of is that the current Download icon is not the icon that lived in my left sidebar for many years. It changed to the current icon, towards the end of my using Vuze, and then became the reappearing/disappearing icon that it is today when I  changed (happily), over to BiglyBT.

Help!  (Also, thank you for all that you do).

Warm Regards,

**Comment by parg** [comment] 2019-05-08 08:55
Ah, I don't really think programming is easy but it isn't so hard that you should be put off playing around a bit with things like tag constraints :)

When BiglyBT hangs/becomes unresponsive it is more often than not because the Java runtime has run out of heap memory. When Java starts it is configured with a maximum amount of memory it will be allowed to use (this is a subset of your computer's available memory, even if your computer has loads of free memory Java will fail with out-of-memory when its configured memory is used up). By default this is 256MB - you can increase this by going to Tools->Options->Startup &  Shutdown (make sure you Mode is set to Advanced in the settings) and set the 'Max Heap Memory' to, say, 512m and restart.

You can also check the 'logs' folder (this is in the BiglyBT config folder) and look for files called thread_1.log and thread_2.log. These contain memory and CPU usage snapshots every 10 seconds. Upload them here and I'll take a look see if there are any clues.

This 'Downloading' sidebar entry problem is weird, The entry is only supposed to normally appear when you have incomplete downloads and it is supposed to automatically disappear when all downloads are complete. Some people didn't like it so an option was added to permanently hide it (Tools->Options->Interface->Display: Show Downloading Entry). When you hit the 'x' to remove the Downloading entry then that effectively unchecks that option so that the Downloading entry is removed and doesn't come back unless to explicitly go into the options and select it again. When it was initially introduced in Vuze there was a bug that lead to the entry randomly not coming back but that was fixed - I've played around and can't reproduce it :( My comment regarding using a tag constraint of '!isComplete()' was a work-around to produce an equivalent to a Downloading entry that didn't disappear when there were no incompletes.

I've probably missed some of your questions, sorry!

**Comment by Swampgirl** [comment] 2019-05-12 15:13
Hi Parg,
Thank you for taking so much time to address my concerns. I truly appreciate it.

I went to change the Java settings in Startup and Shutdown as you suggested, and "Java Options" is no longer present on that page. I tried to load an earlier configuration, and "Java Options" remained missing. Since configuring java VM is different in Macs vs PC, I now do not know what to do.

I remember reading in chat when you were asked to get rid of the Download icon in the sidebar, and who asked you. Is this fair to long-time users who live by the sidebar and not the Library?

I configured the Tag constraint again  (I did so when you first suggested it); the one you suggested a while back, and again, it has no effect. After this recent configuration, It appeared, then disappeared - forever, as it did the first time.

I am tinkering with Java, and have some ideas with regard to scripting - believe it or not. I will report later if I achieve anything remotely useful.

Finally, since Java has changed their policy, only the most recent formulations are available - like Java SDK 12, especially if one uses Homebrew on Mac for installation (they no longer maintain versions in casks).

I have no problem configuring Tags as you have carefully outlined. It is not hard. I just don't really understand what I am doing, or what the configuration means. To that end, I am looking it up and teaching myself. I do not know, from my limited self-instruction why nothing will work to keep either a Tag or the Download icon in the sidebar. It is not configured correctly in the code, as it was a long time ago..... Something is wrong, a bug,  a gremlin.......

Thank you again for all that you do.

Warm Regards

**Comment by parg** [comment] 2019-05-13 13:10
The Java options are only shown if you change your 'mode' to advanced - see Tools->Options->Mode, maybe that's the issue?

Regarding the Downloading section - all that has changed (and not recently, it was done back in Vuze days) is that it was made possible to permanently remove the Downloading section by either clicking the small 'x' on the right (in the same way that other sidebar entries can be closed) or via the config option. If you don't do this then the behaviour is exactly as it has been since forever.

When a tag is shown in the sidebar it will only be removed if you manually close it (via the 'x') so I'm not sure why the new tag that you have created is disappearing - What did you call your new tag? You can set is as visible in the sidebar by going to Tools->Tags Overview and enabling 'show in sidebar' in the settings (for example)

Although we are officially a Java 8 project (that's the lowest version we support) things mainly work on Java 12 so that shouldn't be a particular issue.

**Comment by Swampgirl** [comment] 2019-05-15 17:38
Hi Parg,
Regardless of ability, I've been in "Advanced" mode since 2005. 

Java Options were included on that page until very recently. They are now gone. Trust Me.

![Screen Shot 2019-05-15 at 11 26 14 AM](https://user-images.githubusercontent.com/24909475/57788042-69cb0c80-7704-11e9-8d22-32bd098d8e23.png)

![Screen Shot 2019-05-15 at 11 25 46 AM](https://user-images.githubusercontent.com/24909475/57788233-bf071e00-7704-11e9-86de-8c99317ee8af.png)

Okay I must be doing a very poor job of explaining my experience with the Download Icon Option. You are correct, the Downloading Option (Section), did change back in the Vuze days. When that change was made, a new icon appeared. I promise you, I remember when it happened (however let's say it was not a new icon just for argument's sake; let's say it was always the icon it is now). Whether there was a change in icon is irrelevant and further confuses the issue (which I tend to do). 

In Vuze days (not necessarily the good ol' days by any stretch of the imagination),  if I had the Download Icon Option checked, that Icon remained no matter what if the Download Icon box was checked in Options>Display.  The Download Icon did not disappear if there were complete, incomplete, or no downloads present. It was there, like the New Icon, which is also checked in my configuration. In other words, the Download Icon was static (b/c I always had it checked); it did not just show up if incomplete downloads were present. 

However, for argument's sake, let's say it did disappear if there were no incomplete downloads present. What I know _For Sure_, is that if I began downloading, the Download Icon was present. Between restarts (again for argument's sake, if downloads were present or not present), the Download Icon remained in the sidebar. If the Download Icon was configured to disappear when downloads were not present, there is a good chance that the old configuration behavior remained, since I **rarely** downloaded an altogether new Vuze or OS software version. 

OR, since I was not having the memory/vm issues I am having now, perhaps I remained unaware of the Download Icon appearing only if incomplete downloads were present, because I was not rebooting the software. If I did reboot it, I NEVER had to go into Options>Display, and recheck the Downloads option. Perhaps I always had downloads. I am willing to concede just about anything to get you to understand what is happening now, and has been happening since I have been running BBT.

Since the advent of BBT, the following things happen:

1.   If checked, the Download Option does not hold between restarts, like the New Option does.  
      Instead, it becomes unchecked when a new iteration of BBT downloads (today, I tried to 
      unenroll from the Beta program  (of which I have been a part since the Vuze days), to see if 
      this improves upon the number of times I go into Options>Display and recheck the 
      Downloads Option.  __All Other__ Choices_ I make between software versions remain as I 
      have chosen them in Options; 
      **In the Options Dialogue, no other choice I have made or make arbitrarily disappears 
      between software versions or rebooting.**

2.  When all downloads complete, the Download Icon disappears. _The Download Icon _does not 
    _reappear_ when new downloads are added and started_ (and thus are "incomplete")._  In 
      order  to see these newly added downloads,  I must go into Options>Display; when I do, I find 
     that the Downloads Icon box  _remains _checked__, despite the addition of new downloads. 
     To see what I am downloading, I must then  _uncheck then recheck the Downloads Icon box_. 
    
 3.  If there are active and/or stopped downloads and BBT crashes (because it runs out of virtual
      memory for reasons that remain unknown to me), _the Download Icon in the sidebar does not 
      reappear_ .  I must go back into Options>Downloads, where I may either find the Downloads 
      Icon box still selected (and then I uncheck the box and recheck the box for the Download 
      Icon **and**  my current downloads to reappear)  OR  I find the Download Icon box _un 
      checked_, requiring me to recheck it so that I may see both the Downloads Sidebar Icon _and
      what I am currently_ _downloading_.
    
 4.  Configuring a Tag, exactly as you suggested, at least 5 different times, does not fix any of 
      the above, nor does it make  downloads appear in the GUI, if/when the Download Icon 
      disappears. The tags of the tagged downloads remain visible in the sidebar, but no 
      downloads appear in the GUI when the Download Icon disappears.  

                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

      Couldn't the Download Icon be configured to appear as a static category if one wanted it, or
      not appear at all, if one has no need of it?  The condition that it only appears when 
      downloads are present (incomplete), has not worked on my Mac since I switched over to BBT. 
      I have been doing this mandatory checking and unchecking of the Downloads Icon box for a 
      very long time.
       
      Based on your description of how the Download Icon is supposed to work when checked, I 
      believe  there is a bug that needs to be fixed - perhaps just on Macs with newer OS
      configurations,  like Sierra and Mojave, I'm just guessing.  This was happening before my 
      current difficulties with VM and the constant crashing.

      I think there is a bug.

      Java 12 has not been wildly successful on my machine.  Since I download Java via 
      Homebrew, I could not download Java 8, as that version is no longer available in Homebrew.
      I will try downloading and installing Java 8 manually, and see if my software becomes any 
      happier.  If not, I'm about to reinstall the operating system, and start from scratch, since I 
      can sometimes download 1 torrent at a time, before it crashes.  I'll go work on this and report
      back.

Thank you Again - especially for reading this treatise.

Warm Regards,

**Comment by parg** [comment] 2019-05-16 14:21
The Java Options are only shown if there is a java.vmoptions file in your Application Support/BiglyBT folder - if that has gone AWOL for some reason then it isn't shown as the options can't be updated.

**Comment by parg** [comment] 2019-05-16 14:31
Configuring the Tag wasn't in any way supposed to fix the issue with the 'Downloading Entry' (with the icon with the down pointing arrow next to the text 'Downloading), it creates an entirely separate Tag entry in the sidebar that contains the same downloads that would be shown in the 'Downloading' entry. This separate Tag (call it what you want) would always be present and would take the place of the apparently buggy Downloading entry. And when you say Options->Display: Download Icon box I assume you really mean the checkbox next to the words "Show the 'Downloading' Entry" - just to be sure.

**Comment by parg** [comment] 2019-05-16 15:40
I did a fresh Bigly install on OSX Mojave and 
1) the Java VM Options show up in the config
2) Try as I could the 'Downloading' sidebar entry behaved itself, appearing when there were incomplete downloads and disappearing when they all completed

**Closed** 2019-12-16 11:04 UTC
