### ISSUE TITLE
Search for Existing Data Files Crashes Application

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#502] opened 2018-06-23 22:16 UTC
Java 1.8.0_162 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.5.0.1_B12/4 az3

I've come across a few different scenarios where the process of searching for existing data files is crashing the client. One scenario is where I cancel a search while it's in process. The other is when a search completes but the search window hangs instead of closes upon completion of a search and updates made to files within the torrent with new directory mapping of locations/names of the files found.

FYI.

**Comment by parg** [comment] 2018-06-26 16:40
Hmm, I've played around with it a bit but can't reproduce the problem :( When you say it crashes the client, do you mean the client actually exits and you have to restart it or does it just become unresponsive and you have to force quit it? Also, if the later (and in your second example where it hangs) is BiglyBT sucking up CPU in that state?

**Comment by ms52538** [comment] 2018-06-26 23:36
Hi, the client actually shutdowns on it's own, then it restarts on it's own within 30 seconds of the shutdown, and it demonstrates a load up of all the torrents, and goes through it's normal startup process. I have over 1,000 torrent files inside the library, with files spread out in some cases in 2 different local internal disk drives, across multiple sub-directories, etc. All told there are well over 3,000 files the client is tracking and managing in the library as part of the 1,000 torrent files. | As for sucking up CPU, I'll try to pop up my resource monitor just before I do my next batch of searches and see if I can track its performance on CPU and disk both.

**Comment by parg** [comment] 2018-06-27 07:58
If the client crashes it doesn't auto-restart itself so that is a bit weird. There are various options that can cause restarts (e.g. 'auto restart when idle') but these aren't related to searching for existing data files.

**Comment by parg** [comment] 2018-06-27 08:07
I have managed to reproduce the crash though, yay!

**Comment by parg** [comment] 2018-06-27 19:47
The crash seems to be related to Windows 10 update KB4284848 - I had a VM running on a version prior to this update and couldn't reproduce the issue. On applying the update the crash started occurring frequently.

**Comment by parg** [comment] 2018-06-27 19:57
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536376

**Comment by ms52538** [comment] 2018-06-28 20:19
Yep, I'll do that now. Oddly enough I just had another crash; I had loaded 5 new torrents in a stopped state, selected them, and executed the search against one of the drives, the search ran fine, and then upon completion the client crashed and this time it did NOT restart (as it had been doing before), so I tried to reproduce the same crash again, performing the same search on the same 5 torrents at one time, and the search results came back immediately (sometimes I has to rebuild a cache or something - you'd know certainly, and other times the results return immediately as if it is not even searching). So I headed here to update my status and just saw your posts. I'll updated the Java 10 version you are liking, following your instructions, and will let you know if I suffer another crash. - On a side note; why is it that there are times I will click on Help, then Check for Updates, nothing appears (normally I see a box pop up with a message). Right now I'm on B1.5.0.1_B12/4 az3 - and I'm thinking you already have a 13 or higher release out?  Thanks again for all you do!! I love this client - best out there without question imo.

**Comment by ms52538** [comment] 2018-07-01 02:11
Update: 
With the recent change made to java on the OS, and subsequent upgrade of the client to beta 14, I threw a lot of searches at the client today, over 90 torrents, hundreds of files to search, and the client never crashed. I did have to run a few repeat searches as the first pass was not catching all of the files contained within the torrent, but a second run worked fine - I presume it was just the volume of multiple torrents being included in the same search. So far so good!

**Comment by ms52538** [comment] 2018-07-01 16:11
Update:
The client crashed this morning, after completing an extensive search of 24 torrents with about 300 files.
The initial box that opens, to start the parameters for the search, is the box that hangs upon completion of a search, when the client does crash.

**Comment by ms52538** [comment] 2018-07-02 21:46
Just to validate, I'm still on Beta 14, I have removed the Java folder from Bigly's root install directory under Program Files, Windows 10. I am now able to consistently perform search file tasks which crash the client, rather easily. If I simply look at an existing torrent already setup and 100% checked/validated by BiglyBT (one that has multiple files (and I rename one of those files in the O/S)), Bigly immediately sees it. If I then remove the file from the folder in which BiglyBT thinks it was last stored, into a folder some place else, then perform a search function on that same torrent file within BiglyBT, the client will ultimately crash. | In regards to the error log you had mentioned; I'm not seeing it within my %USER%/AppData/Local/Temp folder, additionally a search of my entire C:\ OS drive does not yield results either. To be sure, I uninstalled and reinstalled the JRE packaged you had linked earlier, and placed a statement in the environment table pointing to it (otherwise BiglyBT will not start) - and still have not been able to see a log file upon crash. Is there a flag option that I'm missing in the Java client?

**Comment by parg** [comment] 2018-07-04 12:46
hmm, that's annoying :( It should be generated by default - no configuration required. You could try running

https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

and use it to monitor file accesses by the BiglyBT process (in an attempt to see where it tries to write the crash dump to). You would need to configure a filter though (process name = BiglyBT.exe) as it generates a massive amount of data

**Comment by parg** [comment] 2018-07-04 21:18
meh - I have also managed to reproduce it on a Java 10 JVM (took a LOT of attempts though) and I also am not seeing a debug file - I tried my own advice with procmon and see no evidence at all that the JVM is attempting to write a dump file :( Given that the SWT guys aren't interested in looking into this I'm not sure how to proceed.

**Comment by ms52538** [comment] 2018-07-05 16:55
Would it help downgrading to an older version of JVx in order to capture the data? I literally am able to readily reproduce the crash. Absolutely love the feature, as it's a godsend. I mean, literally - BiglyBT is a godsend as it bridges the realm of crap torrents loaded with files with a hord of different names and naming conventions - and to the Windows OS level for file management and structure/placement of files; video, images, audio, etc. - and then Plex being able to pick that up and make sense of it. The 'glue' is BiglyBT.  :)  If I were rich, I'd buy you a cup of coffee every day!! :)  Until I start working again, verbal praise is the best I can do. Thanks man.

**Comment by parg** [comment] 2018-07-09 20:39
I think the SWT guys have all they need (apart from time apparently) to look into it. A Java 10 dump crash would be useful as Java 10 is the latest-and-greatest, but they should be able to make progress with the Java 8 one. The weird thing is that BiglyBT pops up windows all of the time but it only seems to be this one that is causing the crash. I've message about for ages with it, seeing if I can spot something unique about it that might cause the crash but have totally failed :( If I get a some spare time I'll try again. Thanks for all your support! When you're rich I'll take you up on your offer :)

**Comment by parg** [comment] 2018-07-10 10:10
Actually I reproduced it in another window (Help->Advanced->Show Configuration Changes...). This re-uses the same component to show the window. I ripped this component out of BiglyBT in an attempt to create a simple stand-alone example of the crash for the SWT guys but of course it doesn't crash...

**Comment by parg** [comment] 2018-07-11 11:36
OK, next beta (B18 when built) has a hack in to re-use the 'search for existing files' window on Windows 10 rather than closing it. I don't like it but it should work around your problem - please report back when the beta is released. Note that I have only attempted to fix the problem in search-for-existing-files, not other places where this component is used.

**Comment by parg** [comment] 2018-07-11 14:46
B!8's now live!

**Comment by ms52538** [comment] 2018-07-11 19:19
On it!! 💯  - though I did have to do another workaround to get update to 18. See my post: https://github.com/BiglySoftware/BiglyBT/issues/505

Thank you Sir!, will let you know how it goes.

**Comment by parg** [comment] 2018-08-07 16:48
OK to close this now I hope?!?

**Closed** 2018-12-23 20:48 UTC
