### ISSUE TITLE
It's impossible to reopen BiglyBT window after it to be minimized to systray on KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [BiglySoftware/BiglyBT#1001] opened 2019-04-15 14:51 UTC
OS and version linux, Arch Linux
For *nix: Desktop Environment KDE Plasma 5.15.4
Java 10.0.2 (64 bit)
Oracle Corporation
/usr/lib/jvm/java-10-openjdk

SWT v4922, gtk/3.24.8, zoom=100, dpi=96
Linux v5.0.7-arch1-1-ARCH, amd64 (64 bit)
B1.9.0.0/4 az3

It's impossible to reopen BiglyBT window after it to be minimized to systray on KDE Plasma desktop environment.  Nothing happens when you click or double-click the BiglyBT icon in systray and when you right click on the systray icon and select "Show BiglyBT".

Steps to reproduce:
open BiglyBT
press ctrl+, to open its options
click "Interface" section in the left side
under System tray", check both "Enable system tray" and "Minimize minimizes to system tray" options, save the settings
Restart BiglyBT
Click the button in the title bar to minimize BiglyBT
Result: the problems mentioned above occur

**Comment by TuxPaper** [comment] 2019-04-15 23:55
Have you tried the "Force usage for Dorkbox SystemTray" option in Interface settings to see if it makes any difference?  YOu can also try moving out the "dorkbox-systemtray.jar" file from ./biglybt/, this will force usage to SWT.  Let me know if either of those things change anything

**Comment by glaubersm** [comment] 2019-04-16 00:13
"Force usage for Dorkbox SystemTray" option is not available in Interface settings.

**Comment by glaubersm** [comment] 2019-05-28 21:23
This bug persists with BiglyBT 2.0.

**Comment by HieronymusCH** [comment] 2019-07-02 16:13
> Have you tried the "Force usage for Dorkbox SystemTray" option in Interface settings to see if it makes any difference?

Yes, same behaviour.

> YOu can also try moving out the "dorkbox-systemtray.jar" file from ./biglybt/, this will force usage to SWT. Let me know if either of those things change anything

I renamed dorkbox-systemtray.jar to dorkbox-systemtray.jar.sic and tried with the option "Force usage for Dorkbox SystemTray" and without.
BiglyBT is not reappearing.

BiglyBT Version: B2.0.0.1_B12/4 az3
System:
KDE-Plasma: 5.15.4
KDE-Framework: 5.56.0
Qt-Version: 5.12.2
Kernel: 5.0.0-20-generic
64bit
openjdk 12.0.1 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 12.0.1+12-Ubuntu-1, mixed mode, sharing)

**Comment by jbesclapez** [comment] 2022-12-04 11:32
Hi there!
Still same issue in latest v3.24
Solution was to delete the dorkbox-systemtray.jar and restart.

**Comment by tidux** [comment] 2023-03-01 02:06
Renaming dorkbox-systemtray.jar to dorkbox-systemtray.jar.disabled and restarting did not fix the issue.  Plasma Wayland, FC37 Kinoite.

**Comment by parg** [comment] 2023-03-01 10:25
Disable 

Options->Interface: Close minimises to System Tray
Options->Interface: Minimise minimises to System Tray

**Comment by o0nd7ots** [comment] 2024-01-11 22:57
I cannot reproduce this.

**Comment by parg** [comment] 2024-01-12 09:56
Closing as nothing's going to happen here, re-open if so desired.

**Comment by glaubersm** [comment] 2024-01-12 11:27
I can reproduce with version 3.5 on two distributions (Arch Linux and neon unstable).
Could anyone reopen this bug report please?

**Comment by glaubersm** [comment] 2024-01-13 12:11
Reopen please.

**Comment by parg** [comment] 2024-01-14 11:12
Default on Linux for close-to-tray and minimise-to-tray is false, don't enable it.

**Closed by parg** 2024-01-14 11:12 UTC
Labels: bug, Linux/Unix

**Comment by glaubersm** [comment] 2024-01-14 11:35
Sure. I do not enable the feature as a workaround. But if it is enabled, it must work.
