### ISSUE TITLE
BiglyBT does not re-open Library (view) on start up

### ISSUE THREAD

**Issue by csylvain** [BiglySoftware/BiglyBT#506] opened 2018-07-01 16:08 UTC
used to happen occasionally after a Beta update but now happens consistently here.

have to open Side Bar and select Library, then close Side Bar to return BiglyBT to the display it had before shutting down.

Java 1.8.0_171 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_171

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.5.0.1_B14/4 az3

Crash dump follows:

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:284)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:64)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:108)
	at com.biglybt.ui.Main.main(Main.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.biglybt.ui.swt.views.skin.sidebar.SideBar.removeItem(SideBar.java:1905)
	at com.biglybt.ui.swt.views.skin.sidebar.SideBarEntrySWT.close(SideBarEntrySWT.java:448)
	at com.biglybt.ui.swt.devices.DeviceManagerUI$categoryView$1.run(DeviceManagerUI.java:4285)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 13 more

**Comment by ferdnyc** [comment] 2018-07-23 17:57
I am seeing this same thing, now that I've set RSSFeed Scanner to load its tab at startup. Before, BiglyBT would open to the Library every time, but now it opens to the plugin instead, which is a bit irritating. 

(I could always turn off startup-loading of the plugin's tab and just bring it up from the menu when I need it, which is probably what I'll do. But it would be nice to be able to keep it available in the sidebar without it completely hijacking BiglyBT.)

**Comment by ferdnyc** [comment] 2018-07-24 11:19
Hm. Well, now I'm confused. I turned off RSSFeed Scanner's "Load tab at startup" option, and its side bar entry is _still there_. But it no longer hijacks my view on load, so basically that got things to exactly what I want. (It just means that option in the RSSFeed Scanner preferences makes even less sense than I thought, with the new interface.)

But trying to reproduce your thing, @csylvain , I haven't had any success. I have both Statistics and UPnP open in the "Plugins & Extras" sidebar group, as well RSSFeed Scanner still there, and on 5 restarts now BiglyBT loads the Library every time. I even left it sitting on Dashboard once (in the Library tab) when I restarted, and it still loaded the Library view on startup. I wonder why it's behaving differently for you?

**Comment by Ben-bit-blip** [comment] 2019-11-28 18:44
Running into this problem now too. The program starts on "console" under the plugins & extra's instead of the library. I have no idea how to change that.

**Comment by ferdnyc** [comment] 2019-11-29 05:19
@Ben-bit-blip Console isn't a plugin, it's always there. Despite the name/placement it's just the standard BiglyBT "system" console, aka **Tools** > **Console** / <kbd>Ctrl</kbd>+<kbd>4</kbd>. (I guess it's one of the "& Extras", more than "Plugins".)

But why BiglyBT would always be _opening_ to the Console, I couldn't tell you.

Have you tried Closing it (× icon or right-click), to remove that sidebar entry? (You can always bring it back again with **Tools** > **Console** or <kbd>Ctrl</kbd>+<kbd>4</kbd>.) Maybe if you quit BiglyBT and re-launch it _without_ the Console entry open, it'll unstick the default view?

**Comment by Ben-bit-blip** [comment] 2019-11-29 10:19
Thanks. Yeah I thought so, because I couldn't find it under plugins. Anyway, I tried a couple of times to press the x icon and restarting, but that didn't work. Console would reappear under Plugins & Extras and be the default view on startup. 

Right-clicking and removing did work however! Strange, but it's fixed, so all is fine.

**Comment by csylvain** [comment] 2019-11-29 13:22
i think it's a race while the various components are starting up. a similar
issue happens when there is a new Beta available and BiglyBT has been
started by clicking on a link associated with BiglyBT (results in 'torrent
file not found' for the link, not the Beta).

**Comment by Ben-bit-blip** [comment] 2019-11-29 15:46
Hmmm, you made me think of something. I was wondering why it kind of magically fixed itself. Maybe I didn't give the program time enough to properly close? At first I would try to close the console, and restart as soon the program icon disappeared from the system tray. After I got the reply from ferdnyc I opened the program to try again and fix it, but is was already fixed. Trying to think back what I had done, I came up with the answer I gave above.

**Comment by ferdnyc** [comment] 2019-11-29 17:28
@Ben-bit-blip 
> Maybe I didn't give the program time enough to properly close? 

That's entirely possible. BiglyBT can take quite a bit of time even after the UI disappears to completely exit, and until the `java` process terminates it isn't _completely_ shutdown. If it's relaunched before the previous instance has completely exited, that could prevent some of the saved state from being updated properly.

I keep a task viewer (in Conky) running on the desktop of the machine I run BiglyBT on, and whenever it's doing any real work the `java` process is always at the top of the list, so if I close BiglyBT I typically watch to make sure it's gone before I launch it again.

For simple program restarts, you can also use the "Restart BiglyBT" option in the File menu, which takes care of that for you.

**Comment by ferdnyc** [comment] 2021-01-30 04:34
@csylvain @Ben-bit-blip @TuxPaper @parg 

The (relatively-)new shutdown progress dialog addresses issues caused by not waiting long enough for the `java` process to fully exit before relaunching, and I haven't personally encountered any problems with BiglyBT not opening to the Library view in quite a while now... is this issue still valid, or can it be closed?

**Comment by csylvain** [comment] 2021-01-30 20:39
there was a change in architecture (new behavior readily observed) causing
the shutdown to no longer "forget" torrents (pending but not yet "OK"ed
when a biglybt update is detected and downloaded).
the library view has been consistently reappearing upon restart.

IOW: yes, i think this can be closed.  thanks!

**Comment by ferdnyc** [comment] 2021-01-31 15:41
@csylvain
> IOW: yes, i think this can be closed.

Great! You can do that. I can't. :wink: (Parg or tuxpaper can as well, of course, if they see this.)

**Comment by parg** [comment] 2021-01-31 16:14
Done!

**Closed by parg** 2021-01-31 16:14 UTC
