### ISSUE TITLE
[Feature request] Add some delay for searching parameters in Settings

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3272] opened 2024-05-31 00:03 UTC
3.6.0.1_B11

1. `Instruments > Settings` must be closed
2. `Instruments > Settings` - settings window (or tab if option set) will open
3. Try to enter anything to the searchbox AFAC, not only one letter - asdasdasdasd for example

There will be a hangup, because (as I understand) there are searches for first letter, then second, then third etc. Lot of cycles
When I try to search word I want to find then I type it fast enough (~900-1500 sym/min) and everytime I got hangups.

If I clear searchbox and type anything again then there no hangups (search caching?). If I close tab/window and open it again then hangs are here again.

PS: tested with just one letter "a" - the same hangs. It hangs about ~5 secs and one or two cores are highly loaded (40-50%) for that time.

Please add some delay after key release (50 ms will be enough I think). Maybe it will fix searching of words.
Because filtering of one letter returns a lot of results a needs a lot of calculations.

**Comment by parg** [comment] 2024-05-31 07:17
Know issue, won't be fixed, caused by the way that all settings views have to be actually created in order to be able to search them,

**Comment by parg** [comment] 2024-05-31 15:13
I slightly speeded up the initial build for the next beta

**Closed by parg** 2024-05-31 15:13 UTC
