### ISSUE TITLE
[Question] How to install BiglyBT on Lubuntu 18.04

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#1193] opened 2019-08-10 09:17 UTC
I hope this question does not sound too dumb, but how do I install BiglyBT 2.0.0 on Lubuntu 18.04? I downloaded the correct installer but once unzipped I am not able to run any of the files inside...

I used previous versions on Lubuntu 16.04 without issue so I am a bit puzzled.

I have Openjdk11.

**Comment by parg** [comment] 2019-08-12 11:09
You should either run the installer directly (don't unzip it) or download the 'Unix tar.gz' installer and unzip that

**Comment by WPFilmmaker** [comment] 2019-08-13 17:21
@parg thanks for the answer! I downloaded the installer and ran it but got:


don't need JNA
not wayland
No suitable Java Virtual Machine could be found on your system.
The version of the JVM must be at least 1.8 and at most 1.12.
Please define INSTALL4J_JAVA_HOME to point to a suitable JVM.

Any idea?

**Comment by TuxPaper** [comment] 2019-08-13 21:06
I was able to reproduce.  Working on a fix.  

fwiw, it's because the latest JVM identifies itself as "11.0.x", "12.0.x", etc, instead of "1.11.x", "1.12.x".  This breaks the "at most 1.12" check, so I'm going to remove the max version check altogether.

**Comment by TuxPaper** [comment] 2019-08-13 21:24
The installer at https://github.com/BiglySoftware/BiglyBT/releases has been updated to have no max JVM version for linux.  www.biglybt.com's installer will be updated within 3-4 hours depending on aws magic.

I've tested it and it works :)  Closing based in that, but let me know if I'm wrong

**Closed by TuxPaper** 2019-08-13 21:24 UTC
