### ISSUE TITLE
Merge all DAT files in "active" folder in configuration directory

### ISSUE THREAD

**Issue by Qwest8K** [BiglySoftware/BiglyBT#1601] opened 2020-04-14 09:58 UTC
As I understand it, files in **%appdata%\Roaming\BiglyBT\active** directory are, in fact, an analogue of **resume.dat** from uTorrent but divided (in my case) into 13 thousand tiny files.

And since BiglyBT constantly reads and writes almost all of them, this creates a big load on my system drive.

Is it possible to somehow optimize the process of accessing to these files. Like combining them into big one and and save in it all the necessary information at certain intervals.

**Comment by parg** [comment] 2020-04-14 10:18
Should only be writing to files corresponding to active torrents, but I'll check things out. There's the option under Options->Files to do with 'saving resume data' - that determines how often an overall save is attempted.

The reason there are separate files per torrent is a trade-off.

**Comment by hatewesterncivilization** [comment] 2020-04-14 13:20
I have >300 thousands these files. Using now built-in backup feature, found it just good. 

Good, folder of Bigly on ram-disk - fast start and exiting and non-bottleneck processes at all, and even Adopt's binaries in the ram.

**Comment by parg** [comment] 2020-04-14 16:44
Try beta B22 - it should write less frequently to the active folder

**Comment by Qwest8K** [comment] 2020-05-31 01:05
@hatewesterncivilization Can you explain how make BiglyBT a portable? I lost all my settings and torrents with last system crush (due to HDD broken), and I don't want this to happen again.

**Comment by Qwest8K** [comment] 2020-08-30 15:50
Is it possible to just move the Active folder to another drive? Because the situation with overload of system drive hasn't changed at all.

**Comment by parg** [comment] 2020-08-30 17:02
How many of your torrents are actually seeding/downloading or queued? The only ones that should be causing file writes since my change are those that are actually seeding or downloading at some point,

**Comment by Qwest8K** [comment] 2020-08-30 17:17
Right now ~7500 simultaneously active downloads and seedings. And because of this, my HDD with 10,000 rpm buzzes like a chainsaw.

**Comment by parg** [comment] 2020-08-31 07:43
Is there a lot of rotation of the seeding torrents from queued->seeding and back? I could add an option to disable all interim state saves (at the risk of losing download info on a crash) but this might not help if you have a lot of rotation going on.

**Comment by Qwest8K** [comment] 2020-08-31 15:59
No one. I made all torrents were fully active.

**Comment by parg** [comment] 2020-09-01 15:08
B29 has a new option under Files to disable interim state saves (below the resume data settings) - tell me how that works

**Comment by Qwest8K** [comment] 2020-09-08 20:48
It works nothing. 

Looks like the only way - it's place Active folder on RAM disk. That is, in any way to force the program to store and process files in RAM (since it wears out many times slower than the fastest SSDs) and dump files to non-volatile storage only when the program is closed.

And I have already taken care about powerful UPS with automatic PC shutdown.

**Comment by parg** [comment] 2020-09-09 05:54
So you enabled that option and are still seeing writes to the active folder?

**Comment by Qwest8K** [comment] 2020-09-09 07:38
Yes.

**Comment by parg** [comment] 2020-09-09 09:32
Well I don't know what's causing those writes then as with that enabled wites should only occur when a download stops/queues or BiglyBT closes down

**Comment by parg** [comment] 2020-09-09 15:46
I'll create a separate log file when that option is enabled to record where the writes are being triggered from

**Comment by parg** [comment] 2020-09-11 13:35
Try B32. When that option is enabled a log file is written to the usual logs directory called

DownloadStateSaves_1/2.log

Every time a file is written in the 'active' directory an entry is logged detailing the cause - you should see a lot of activity

**Comment by parg** [comment] 2020-09-11 13:51
B33 I mean, B32 was missing changes

**Comment by Qwest8K** [comment] 2020-09-12 09:39
Okay, that is history from log file of one of my torrents.
[DownloadStateSaves_1.zip](https://github.com/BiglySoftware/BiglyBT/files/5212486/DownloadStateSaves_1.zip)
Complete log, by the way, had at the time ~70 MB in size.

**Comment by parg** [comment] 2020-09-12 12:28
Interesting - those are interim resume data saves. I'll look into it but in the meantime you could reduce this by changing your '1 minute' setting under Files to something larger (the default is 5 minutes)

**Comment by Qwest8K** [comment] 2020-09-12 13:09
I guessed (by looking at words "resume" in log) to change time of resume data update (to 240 minutes), but it does not get visible improvements - new lines in log file anyway appearing every second.

So I rolled back to a every one minute update.

**Comment by parg** [comment] 2020-09-12 15:33
Try B34 - see if that helps

**Comment by parg** [comment] 2020-09-18 11:35
Any updates on this?

**Comment by Qwest8K** [comment] 2020-09-19 02:06
Well, it seems that system HDD has stopped buzzing and BiglyBT loads it minimally.

**Comment by parg** [comment] 2020-09-19 08:21
Feel free to close the issue then

**Closed** 2020-09-19 20:36 UTC
