### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by afberendsen** [BiglySoftware/BiglyBT#2997] opened 2023-07-01 11:22 UTC
Let me know what additional information do you need to investigate this crash.

```
SWT WebKitGDBus: error creating DBus server Error binding to address (GUnixSocketAddress): No such file or directory
SWT WebKit: error initializing DBus server, dBusServer == 0

(BiglyBT:2841599): GLib-GIO-CRITICAL **: 12:52:14.446: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER (server)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f669d436e16, pid=2841599, tid=2841871
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc38) (17.0.7+7, mixed mode, sharing, tiered, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4942r22.so+0x36e16]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/afberendsen/biglybt/core.2841599)
#
# An error report file with more information is saved as:
# /home/afberendsen/biglybt/hs_err_pid2841599.log
Compiled method (c1) 9859406 32810       3       org.eclipse.swt.internal.Converter::cCharPtrToJavaString (39 bytes)
 total in heap  [0x00007f6f0d2ab090,0x00007f6f0d2ab710] = 1664
 relocation     [0x00007f6f0d2ab1f0,0x00007f6f0d2ab268] = 120
 main code      [0x00007f6f0d2ab280,0x00007f6f0d2ab540] = 704
 stub code      [0x00007f6f0d2ab540,0x00007f6f0d2ab5c0] = 128
 oops           [0x00007f6f0d2ab5c0,0x00007f6f0d2ab5c8] = 8
 metadata       [0x00007f6f0d2ab5c8,0x00007f6f0d2ab5d0] = 8
 scopes data    [0x00007f6f0d2ab5d0,0x00007f6f0d2ab668] = 152
 scopes pcs     [0x00007f6f0d2ab668,0x00007f6f0d2ab708] = 160
 dependencies   [0x00007f6f0d2ab708,0x00007f6f0d2ab710] = 8

(process:3570863): Gtk-WARNING **: 12:52:14.514: Locale not supported by C library.
        Using the fallback 'C' locale.
Compiled method (n/a) 9859410 12899     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f6f15327810,0x00007f6f15327b88] = 888
 relocation     [0x00007f6f15327970,0x00007f6f153279a0] = 48
 main code      [0x00007f6f153279a0,0x00007f6f15327b80] = 480
 oops           [0x00007f6f15327b80,0x00007f6f15327b88] = 8
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk-portable&version=38
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/home/afberendsen/biglybt/biglybt: line 227: 2841599 Aborted                 (core dumped) ${JAVA_PROGRAM_DIR}java -Xmx32g -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Exit from BiglyBT complete
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @12f40c25
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:242)
        at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:85)
        at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
        at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
        at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:303)
        at com.biglybt.platform.unix.ScriptAfterShutdown.main(ScriptAfterShutdown.java:43)
DEBUG::Sat Jul 01 12:54:10 CEST 2023::com.biglybt.core.config.COConfigurationManager::addAndFireParameterListener::617:
  Failed to update 'preferIPv6Address'
    ConfigurationChecker::setSystemProperties::103, ConfigurationManager::initialise::177, ConfigurationManager::getInstance::110, COConfigurationManager::getStringParameter::303, ScriptAfterShutdown::main::43
java.lang.reflect.InaccessibleObjectException: Unable to make field static final transient int java.net.InetAddress.preferIPv6Address accessible: module java.base does not "opens java.net" to unnamed module @12f40c25
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.biglybt.core.config.impl.ConfigurationChecker$1.parameterChanged(ConfigurationChecker.java:135)
        at com.biglybt.core.config.COConfigurationManager.addAndFireParameterListener(COConfigurationManager.java:617)
        at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:103)
        at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
        at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
        at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:303)
        at com.biglybt.platform.unix.ScriptAfterShutdown.main(ScriptAfterShutdown.java:43)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.SESecurityManagerImpl (file:/home/afberendsen/biglybt/BiglyBT.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.SESecurityManagerImpl
WARNING: System::setSecurityManager will be removed in a future release
No shutdown tasks to do
BiglyBT TERMINATED.
```

**Comment by parg** [comment] 2023-07-01 13:51
Unfortunately I'm not able to investigate native crashes in the SWT UI library we use :(

**Comment by axredneck** [comment] 2023-09-16 20:39
A duplicate of #3047 ?

**Closed** 2024-01-13 12:14 UTC
