### ISSUE TITLE
using BiglyBT in k3b

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2321] opened 2021-11-09 02:44 UTC
I am really grateful for BiglyBT's Search for Existing Data Files function.  I know I wish k3b had something like that, to deal with bad sectors, that maybe if I had 2 or 3 copies of a dvd, all the good sectors could be pooled together to make a dvd with fewer or no bad sectors.

**Comment by ferdnyc** [comment] 2021-11-26 03:32
@as-muncher The problem is, how could it know?

BiglyBT's piece-management functionality works because every piece of a BitTorrent share is checksummed ahead of time, which allows it to maintain a map of which pieces are valid and which aren't. k3b has no way of telling a good DVD image from a bad one, or of telling which sectors are valid and which aren't.

There _have been_ other tools that offered functionality along those lines, including checksumming images. [EAC](https://www.exactaudiocopy.de/en/) (which stands for Exact Audio Copy) comes immediately to mind — it's a Windows tool for making archival copies of music CDs and DVDs by tracking good vs. bad sectors while ripping.

But the EAC developers will be the first to warn, the problem is that consumer drives **can't** (or at least _won't_) provide accurate data about good and bad sector reads during the ripping process. Any software that wants to ensure a flawless read is ultimately forced to resort to effectively just _guessing_ which data is valid and which isn't. (Either that, or retrying each rip multiple times and checking for any blocks that change from read to read, an incredibly time-consuming process.

When creating a torrent, a known-good and known-complete copy of the original file is used to create the checksums that can later be used to validate partial downloads. But without having a complete original file and collecting the necessary data ahead of time, the information just isn't readily available to reconstruct it from partial data later.

**Comment by as-muncher** [comment] 2021-11-28 23:25
@ferdnyc I just thought that maybe k3b would mark which sectors of the CD it had trouble reading, because if it can say that it had an error while reading, maybe it might mark that on the new CD or DVD and then if there were good sectors on another DVD, then it could merge them to make a good DVD.  But thanks for the thoughtful response.  I enjoyed reading it.

**Comment by ferdnyc** [comment] 2021-11-29 01:58
@as-muncher \*nod* I think K3b, specifically, isn't really about recovering _bad_ media — that requires a whole set of tools that are kind of outside of K3b's targeted featureset, and would only be useful to a tiny percentage of its userbase — too small a percentage to justify including those features, probably.

(Another issue is that even having "the same DVD" doesn't mean the contents are **identical**. Which they would have to be, in order to use one disc to recover a damaged image from another. There must be dozens of different iterations of any given DVD release, all with different filesystem contents or layouts. Which may then be translated into even _more_ different possible image files. The type of checksum-style recovery offered by BitTorrent clients requires byte-for-byte identical (though incomplete) files. But disc images of even the exact same disc will vary (and therefore be incompatible) depending on the software used, the options selected while creating it, etc.)

There _are_ tools that can be employed for the purpose of recovering damaged discs. dvdisaster (which I guess lives at https://dvdisaster.jcea.es/ now) is the first one that springs to mind. It works by effectively creating the equivalent of a .torrent file's checksum data, for the disc image contents — the part that I mentioned K3b not having, in order to do recovery.

The [user manual](https://dvdisaster.jcea.es/downloads/manual.pdf) even discusses a scenario where two different (damaged) copies of a disc are used, along with an after-the-fact error-correction scan, to construct a working "good" image for the disc. (They mention that as an un-ideal scenario, of course, since the intent of dvdisaster is to collect data from a **good** disc _before_ it's needed for recovery — much like a .torrent file's checksums are constructed from the intact file, before it's (potentially) transferred incomplete to other peers.)

**Comment by ferdnyc** [comment] 2021-11-29 03:29
Oh, hah! Except for one major shortcoming I forgot about: dvdisaster doesn't support factory-pressed CD-ROM, DVD-ROM, or BD-ROM discs — only writable ±R/RW and -RAM discs. Also, no audio CDs even if burned.

(This is explicitly a legal consideration, otherwise dvdisaster checksum data could theoretically be distributed and used to duplicate commercial media, by enabling "reconstruction" of copy-protected disc contents.)

**Closed** 2021-12-02 02:55 UTC
