### ISSUE TITLE
Magnet URI metadata downloads not persistent across restarts

### ISSUE THREAD

**Issue by Omni-Consumer-Products** [BiglySoftware/BiglyBT#1813] opened 2020-10-02 20:24 UTC
Hello,

After updating to 2.5.0.0 (running Windows 10) Magnet URIs that are in the process of downloading are no longer persistent between Bigly resets - they were before the 2.5.0.0 update as 'metadata download' torrents as described by parg in this issue (https://github.com/BiglySoftware/BiglyBT/issues/1803).

My Magnet URI Handler plugin options are:
Enable
Delay=20
Overall lookup timeout=0
Add yourself...=Shares
Additional peers...=0
Recover magnet downloads across restart=checked
Recovery concurrency=32
Rename downloads=not checked
Default networks all checked: Public IP, I2P, Onion

Any ideas?
Thanks!

**Comment by parg** [comment] 2020-10-03 08:31
Hmm, works for me - I assume you mean 'restart' not 'reset' - a reset of configuration data will result in magnet downloads being lost as they are stored in configuration data (and always have been)

**Comment by Omni-Consumer-Products** [comment] 2020-10-03 13:14
Hi Parg.  Yes, I meant restarts - not resets of the config data.

I know this worked for me within the last month - and I'm pretty sure I haven't changed any other options lately.  I'd hate to reset the config to all defaults since I've been tweaking the options for many years and I'd never be able to remember all the settings I've changed...

I just tried again to be sure.  I started downloading a magnet that doesn't have lots of sources, after 20 seconds the metadata download shows up the downloading pane, I wait a few more seconds then File->Restart BiglyBT, when it comes back up the metadata download is gone.

Maybe there is some other setting I have that's conflicting with this one?

**Comment by parg** [comment] 2020-10-03 13:38
Can't think of anything that would conflict - I am using exactly the same settings as you and things recover OK :(

**Comment by parg** [comment] 2020-10-03 13:41
Check your debug_1/2.log files in the 'logs' folder of the BiglyBT config dir

**Comment by Omni-Consumer-Products** [comment] 2020-10-04 01:48
Debug log 1 timestamp is a couple days old.  But debug log 2 has recent content.  I think this is the log from the restart I did in my post from today (I didn't see a way to paste formatted text - I selected insert code but I'm not sure that helped make it look any better):
`
[09:06:32] [stderr] Warning - No client apps or router console configured - we are just a router
[09:23:35] DEBUG::Sat Oct 03 09:23:35 EDT 2020  Only non-daemon bootstrap thread remaining, exiting...

[10/3/20 9:23 AM] Log File Opened for BiglyBT 2.5.0.0
[09:23:38] [stderr] DEBUG::Sat Oct 03 09:23:38 EDT 2020::com.biglybt.core.util.NetUtils$1::run::122:
[09:23:38] [stderr]   Network interface enumeration took 418: increased refresh frequency to 120000ms
[09:23:38] [stderr]     NetUtils$2::run::193, AEThread2$threadWrapper::run::317
[09:23:41] [stderr] INFO: Native CPUID library jcpuid-x86-windows.dll loaded from resource
[09:23:42] [stderr] INFO: Loaded library: jar:file:/C:/Users/X/AppData/Roaming/BiglyBT/plugins/azneti2phelper/jbigi-win_0.4.jar!/jbigi-windows-coreihwl_64.dll
[09:23:42] [stderr] INFO: Native BigInteger library jbigi-windows-coreihwl_64.dll loaded from resource
[09:23:45] [stderr] DEBUG::Sat Oct 03 09:23:45 EDT 2020::com.biglybt.plugin.magnet.MagnetPluginMDDownloader::startSupport::952:
[09:23:45] [stderr]     MagnetPluginMDDownloader::access$0::190, MagnetPluginMDDownloader$1::run::123, AEThread2$threadWrapper::run::317
[09:23:45] [stderr] java.lang.NullPointerException
[09:23:45] [stderr] 	at com.biglybt.core.global.impl.GlobalManagerImpl.addDownloadManager(GlobalManagerImpl.java:1051)
[09:23:45] [stderr] 	at com.biglybt.core.global.impl.GlobalManagerImpl.addDownloadManager(GlobalManagerImpl.java:970)
[09:23:45] [stderr] 	at com.biglybt.core.global.impl.GlobalManagerImpl.addDownloadManager(GlobalManagerImpl.java:955)
[09:23:45] [stderr] 	at com.biglybt.pifimpl.local.download.DownloadManagerImpl.addNonPersistentDownloadStopped(DownloadManagerImpl.java:499)
[09:23:45] [stderr] 	at com.biglybt.plugin.magnet.MagnetPluginMDDownloader.startSupport(MagnetPluginMDDownloader.java:340)
[09:23:45] [stderr] 	at com.biglybt.plugin.magnet.MagnetPluginMDDownloader.access$0(MagnetPluginMDDownloader.java:190)
[09:23:45] [stderr] 	at com.biglybt.plugin.magnet.MagnetPluginMDDownloader$1.run(MagnetPluginMDDownloader.java:123)
[09:23:45] [stderr] 	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
[09:23:45] java.lang.NullPointerException
	at com.biglybt.core.global.impl.GlobalManagerImpl.addDownloadManager(GlobalManagerImpl.java:1051)
	at com.biglybt.core.global.impl.GlobalManagerImpl.addDownloadManager(GlobalManagerImpl.java:970)
	at com.biglybt.core.global.impl.GlobalManagerImpl.addDownloadManager(GlobalManagerImpl.java:955)
	at com.biglybt.pifimpl.local.download.DownloadManagerImpl.addNonPersistentDownloadStopped(DownloadManagerImpl.java:499)
	at com.biglybt.plugin.magnet.MagnetPluginMDDownloader.startSupport(MagnetPluginMDDownloader.java:340)
	at com.biglybt.plugin.magnet.MagnetPluginMDDownloader.access$0(MagnetPluginMDDownloader.java:190)
	at com.biglybt.plugin.magnet.MagnetPluginMDDownloader$1.run(MagnetPluginMDDownloader.java:123)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)

[09:23:45] [stderr] java.net.SocketException: Network is unreachable: connect
[09:23:45] [stderr] 	at sun.nio.ch.Net.connect0(Native Method)
[09:23:45] [stderr] 	at sun.nio.ch.Net.connect(Unknown Source)
[09:23:45] [stderr] 	at sun.nio.ch.DatagramChannelImpl.connect(Unknown Source)
[09:23:45] [stderr] 	at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:221)
[09:23:45] [stderr] 	at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
[09:23:45] [stderr] 	at lbms.plugins.mldht.azureus.MlDHTPlugin$9.runSupport(MlDHTPlugin.java:670)
[09:23:45] [stderr] 	at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:161)
[09:23:45] [stderr] 	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
[09:23:46] [stderr] Warning - No client apps or router console configured - we are just a router
[09:26:46] [stderr] DEBUG::Sat Oct 03 09:26:46 EDT 2020::com.biglybt.core.util.ThreadPool::checkWarning::368:
[09:26:46] [stderr]   Thread pool 'Simple Timer' is full (busy=delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect)
[09:26:46] [stderr]     ThreadPool::run::246, ThreadPool::run::213, Timer::runSupport::342, AERunnable::run::36, Thread::run::-1
[16:37:17] [stderr] DEBUG::Sat Oct 03 16:37:17 EDT 2020::com.biglybt.core.download.impl.DownloadManagerImpl::setTorrentFile::5423:
`

Could the "java.lang.NullPointerException" just after the "MagnetPluginMDDownloader::access..." be a problem?

**Comment by parg** [comment] 2020-10-04 07:54
Yup, well spotted :)

It is caused by a bug that is triggered by you having 'Resume Downloads On Start' enabled - think it has been there a while.

I'll fix it for the next beta but in the meantime disabling that feature should cure things.

Thanks

**Comment by Omni-Consumer-Products** [comment] 2020-10-04 13:09
Yes, disabling the resume fixed it for me.  Thanks!

I'm a C++ guy, but I've looked at a lot of logs and fixed a bunch of exceptions (usually my own :) ) through the years.

Thanks for your help!   And thank you for your work on Bigly!!

Let me know if you'd like me to close this issue.

**Comment by parg** [comment] 2020-10-04 13:25
Glad it worked! Feel free to close the issue, I'm sure my fix will be fine :)

**Closed** 2020-10-04 13:26 UTC
