### ISSUE TITLE
Remove Files no longer removing torrent files

### ISSUE THREAD

**Issue by nofnway** [BiglySoftware/BiglyBT#1360] opened 2019-11-24 14:17 UTC
Hi,
This seems to have crept in around B27 or B28 - When you remove files from uploads in the UI, and the remove torrent file box is checked and the remove all box is checked, it removes the data files, but then the torrents are re-added to the downloads section like they are starting over. Removing the files again from downloads removes them from the UI for good. This wasn't the previous or expected behavior. Please review/resolve.
Thanks!

* WIn 10 1909 build 18363.476
* BiglyBT Version 2.1.0.1 B30

**Comment by parg** [comment] 2019-11-24 15:40
Does this happen every time? I've tried but can't reproduce it :( Are the downloads actually added in a state where they proceed to download or is it some weird UI artifact?

**Comment by nofnway** [comment] 2019-11-25 22:21
Hi Parg,
The files are in the uploads section. Have reached 1:1, and are in a queued, 1:1 ratio met state from queing rules, so am removing via highlight them all, click the remove button, check all files, checked torrent files too, then delete, but within a min, the files reappear in the downloads section as incomplete, like the torrent just got added. If I then remove those new files again from the downloads section, using same steps, then they are gone for good. Does this help?
Thanks!

**Comment by parg** [comment] 2019-11-26 08:42
Do you have any auto-import folders configured? Or how about a Subscription marked as 'auto-download' or an RSS plugin that might be adding the downloads? If you check 'Download History' (View menu) do you see the downloads being added (again?).

Perhaps you could reproduce the issue and send a debug.zip (Help menu, last option, perhaps rename to debugzip to avoid any AV issues) and email over to paul@biglybt.com ?

**Comment by mboland** [comment] 2020-02-03 02:48
I am experiencing the same issues.
Delete the torrent from the computer in the UI but it does not remove the torrent only the data.
So you have the torrent reloading into the UI.
Mac OS X 10.15.3 Beta (19D62e)
Mac Pro (Late 2013)

Files are on an external 2Tb USB drive

**Comment by parg** [comment] 2020-02-03 10:54
Are you saying that the download remains in BiglyBT's library or that the .torrent file is remaining on your hard drive when you expect it to be deleted along with the data?

Perhaps you could create a debug.zip as mentioned in my previous post and send it over?

**Comment by mboland** [comment] 2020-03-10 00:29
Had a few other issues with BiglyBT like no items appearing in parameter window.
Moved Torrents to a different external drive, reloaded BiglyBT from scratch made little difference but the last update seemed to fix it all so operational expected now.

**Closed** 2024-01-13 12:05 UTC
