### ISSUE TITLE
piece marked as complete but not yet allocated

### ISSUE THREAD

**Issue by kwloafman** [BiglySoftware/BiglyBT#269] opened 2018-01-08 12:17 UTC
I've got a torrent with one piece missing and I'm getting this in the console log for that torrent.  Is this something I can fix or just "something that happens".

...Thanks,
...Ken

```
Java 1.8.0_151 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4528, cocoa
Mac OS X v10.13.2, x86_64 (64 bit)
B1.2.0.1_B33/4 az3
```

```
[06:05:51.958] {stderr} DEBUG::Mon Jan 08 06:05:51 CST 2018::com.biglybt.core.disk.impl.access.impl.DMCheckerImpl$5$1::complete::832:
[06:05:51.958] {stderr}     run (ConcurrentHasherRequest.java:159), runSupport (ConcurrentHasher.java:146), AERunnable.run, ThreadPool.runIt
[06:05:51.958] {stderr} com.biglybt.core.diskmanager.cache.CacheFileManagerException: piece marked as complete but not yet allocated
[06:05:51.958] {stderr} 	at com.biglybt.core.diskmanager.cache.impl.CacheFileManagerImpl.rethrow(CacheFileManagerImpl.java:957)
[06:05:51.966] {stderr} 	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.setPieceComplete(CacheFileWithCache.java:1564)
[06:05:51.966] {stderr} 	at com.biglybt.core.disk.impl.access.impl.DMCheckerImpl$5$1.complete(DMCheckerImpl.java:825)
[06:05:51.966] {stderr} 	at com.biglybt.core.util.ConcurrentHasherRequest.run(ConcurrentHasherRequest.java:159)
[06:05:51.966] {stderr} 	at com.biglybt.core.util.ConcurrentHasher$2$1.runSupport(ConcurrentHasher.java:146)
[06:05:51.966] {stderr} 	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
[06:05:51.966] {stderr} 	at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:328)
[06:05:51.966] {stderr} 	at com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:736)
[06:05:51.966] {stderr} 	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:295)
[06:05:51.966] {stderr} Caused by: com.biglybt.core.diskmanager.file.FMFileManagerException: piece marked as complete but not yet allocated
[06:05:51.966] {stderr} 	at com.biglybt.core.diskmanager.file.impl.FMFileAccessPieceReorderer.setPieceComplete(FMFileAccessPieceReorderer.java:677)
[06:05:51.966] {stderr} 	at com.biglybt.core.diskmanager.file.impl.FMFileAccessController.setPieceComplete(FMFileAccessController.java:441)
[06:05:51.966] {stderr} 	at com.biglybt.core.diskmanager.file.impl.FMFileImpl.setPieceCompleteSupport(FMFileImpl.java:706)
[06:05:51.966] {stderr} 	at com.biglybt.core.diskmanager.file.impl.FMFileLimited.setPieceComplete(FMFileLimited.java:217)
[06:05:51.966] {stderr} 	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.setPieceComplete(CacheFileWithCache.java:1560)
[06:05:51.966] {stderr} 	... 7 more
```

**Comment by parg** [comment] 2018-01-14 08:54
Sorry for the delay in replying - did the download ever complete? If not could you try a 'force recheck' on it?

**Comment by kwloafman** [comment] 2018-01-14 17:23
It has not completed yet.  _Full Copy Seen_ is always today's date, so I'll catch that peer someday.

Did a force recheck and a lot of those errors occurred.  The traceback does not mention what file, but all of the pieces around it passed hash check.  The piece map has only one piece missing, but it did not encounter any errors near it.  All of this could be invalid, of course, if stdout and stderr are buffered.  To my reading, it sounds like the data on the disk is OK, but some table is badly screwed up.

Is there a way to get the console to log to file?

```
[11:01:35.818] {disk} Piece 3441 passed hash check.; 	| TorrentDM: '<redacted>'
[11:01:35.820] {disk} Piece 3442 passed hash check.; 	| TorrentDM: '<redacted>'
[11:01:36.020] {disk} Piece 3443 passed hash check.; 	| TorrentDM: '<redacted>'
[11:01:36.021] {stderr} DEBUG::Sun Jan 14 11:01:36 CST 2018::com.biglybt.core.disk.impl.access.impl.DMCheckerImpl$5$1::complete::832:
[11:01:36.023] {stderr}     run (ConcurrentHasherRequest.java:159), runSupport (ConcurrentHasher.java:146), AERunnable.run, ThreadPool.runIt
[11:01:36.023] {stderr} com.biglybt.core.diskmanager.cache.CacheFileManagerException: piece marked as complete but not yet allocated
[11:01:36.023] {stderr} 	at com.biglybt.core.diskmanager.cache.impl.CacheFileManagerImpl.rethrow(CacheFileManagerImpl.java:957)
[11:01:36.023] {stderr} 	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.setPieceComplete(CacheFileWithCache.java:1564)
[11:01:36.024] {stderr} 	at com.biglybt.core.disk.impl.access.impl.DMCheckerImpl$5$1.complete(DMCheckerImpl.java:825)
[11:01:36.024] {stderr} 	at com.biglybt.core.util.ConcurrentHasherRequest.run(ConcurrentHasherRequest.java:159)
[11:01:36.024] {stderr} 	at com.biglybt.core.util.ConcurrentHasher$2$1.runSupport(ConcurrentHasher.java:146)
[11:01:36.024] {stderr} 	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
[11:01:36.024] {stderr} 	at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:328)
[11:01:36.024] {stderr} 	at com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:736)
[11:01:36.024] {stderr} 	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:295)
[11:01:36.024] {stderr} Caused by: com.biglybt.core.diskmanager.file.FMFileManagerException: piece marked as complete but not yet allocated
[11:01:36.024] {stderr} 	at com.biglybt.core.diskmanager.file.impl.FMFileAccessPieceReorderer.setPieceComplete(FMFileAccessPieceReorderer.java:677)
[11:01:36.024] {stderr} 	at com.biglybt.core.diskmanager.file.impl.FMFileAccessController.setPieceComplete(FMFileAccessController.java:441)
[11:01:36.024] {stderr} 	at com.biglybt.core.diskmanager.file.impl.FMFileImpl.setPieceCompleteSupport(FMFileImpl.java:706)
[11:01:36.024] {stderr} 	at com.biglybt.core.diskmanager.file.impl.FMFileLimited.setPieceComplete(FMFileLimited.java:217)
[11:01:36.024] {stderr} 	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.setPieceComplete(CacheFileWithCache.java:1560)
[11:01:36.024] {stderr} 	... 7 more
[11:01:36.039] {disk} Piece 3444 passed hash check.; 	| TorrentDM: '<redacted>'
[11:01:36.041] {disk} Piece 3445 passed hash check.; 	| TorrentDM: '<redacted>'
[11:01:36.192] {disk} Piece 3446 passed hash check.; 	| TorrentDM: '<redacted>'
```

**Comment by kwloafman** [comment] 2018-01-15 12:44
I think we are chasing a ghost.  No matter which torrent console I look at, I see this traceback, even on torrents in the queued state.  I don't think the traceback is necessarily related to the torrent console I'm looking at.  It seems to be dumped to all consoles.

...Ken

**Comment by parg** [comment] 2018-01-15 15:03
The weird thing in that log is that although the error occurs the pieces seem to be being marked as 'passed hash check'...

I don't suppose you could send me the torrent that is failing, in case it is something specific to it? email it to parg@users.sf.net if you can

**Comment by kwloafman** [comment] 2018-01-16 11:39
Figured it out!  I checked all of my torrents and a few went back to download status.  The error is not showing up any more, so it appears to me that _stderr is leaking to whatever console is active and is not tied to the torrent of the active torrent console_.  I was seeing this error with other torrents as well, some of which passed the forced checks.

**Comment by parg** [comment] 2018-01-16 11:47
Good - bit of an odd one that one. If it recurs and you can track it to a specific torrent then please consider sending it over to see if I can reproduce. You're right about the error log - it is generated in a way (as are a lot of the unexpected ones) that isn't tied to the torrent in question. Unfortunately this isn't something easily fixable as torrent context gets lost across subsystems/threads etc. so it is something to be aware of.

**Comment by nwks** [comment] 2018-03-26 15:12
Hi! I just found this report looking for information about this same error that I'm facing continuously, and which causes my client to reject as much as half the size of each torrents I download.

In my case it seems to be linked to the somewhat exotic cache settings I use. I have an extremely fast broadband (1Gbps) and a lot of RAM so I configured the cache in BiglyBT in "Performance Options" as high as possible: size of 2000 MB, and 1024MB of maximum write requests queue.
I understand that this may be a bit over the top but in my case I mostly download on private trackers where I reach easily 50MB/s as download speed.
However it seems that at such speed and cache size, when a piece is finished and the client tries to validate it there's a 50/50 chance that it will fail. My guess is that the piece is temporarily in a cache state that do not allow hash checking, or that the hash routine requires the piece to be available on disk, but it has not yet been flushed (hence the "not yet allocated" bit in the error).

The last one seems the most probable as I found that checking the box "Write complete pieces to disk immediately." completely eliminates the issue. But it obviously defeats the purpose of having a cache for downloading.
Using the option "Allocate and zero new files on creation" also eliminates the issue but it's not really usable for large torrents so I use "incremental file creation" or "append data to files and reorder".

Here is my cache settings:
![cache_settings](https://user-images.githubusercontent.com/29673281/37914450-88488c02-3117-11e8-80ba-81bddff82f97.PNG)

**Comment by parg** [comment] 2018-03-28 08:46
Interesting - thank for the info! As you have discovered, the 'piece re-order' file access mechanism is incompatible with the 'don't flush piece to disk' option (but only causes the issue you are seeing when the check complete process gets ahead of the async data write from the cache. I'll see what I can do.

**Comment by parg** [comment] 2018-03-28 17:21
Please checkout Beta B35 and see if that helps.

**Comment by nwks** [comment] 2018-03-31 15:08
Thank you, the error indeed no longer occurs with the latest beta, with either "incremental file creation" or "append data to files and reorder". However it seems that disk activity is higher / the cache is less effective, which is logical if the patch forces flushes when completing pieces.

I guess it would be better if we could fully complete pieces in-cache and flush them asynchronously, but something tells me it may be a bit more complicated.

**Comment by parg** [comment] 2018-03-31 20:18
Hmm, my change forced a flush-to-disk from the cache after a piece check completed, but not cache eviction. So not sure why things would be worse - after all the content has to be written to the disk at some point and it is left in cache after the write for any potential read-cache hits on announcing piece availability to the swarm.

**Closed** 2019-12-16 11:02 UTC
