### ISSUE TITLE
Completed Torrents return to incomplete status.

### ISSUE THREAD

**Issue by HJKaye** [BiglySoftware/BiglyBT#2780] opened 2022-11-06 00:00 UTC
System: Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=200, dpi=84
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.0/4 az3

* Windows 11 22H2
* BiglyBT Version Number 3.2.0.0

Frequent problem been happening for many months.   Often, a completed torrent, sometimes from many months ago, reappear in the incomplete torrents list. The save path shows on the correct path, the files are there, but no content, downloaded total shows=size or more. Doing a force re-check does nothing, I don't know how to determine why the file(s) moved back to incomplete status. Help?

**Comment by ferdnyc** [comment] 2022-11-06 01:23
Hmm, that sounds very strange @HJKaye !

When you say,
> the files are there, but no content
...do you mean the files are _empty_? (IOW, they don't contain the downloaded data anymore?) If so, was the data present BEFORE the torrent returned to incomplete status, to the best of your knowledge? Or were the files previously moved/deleted from the download location?

If the latter, an active torrent that's had its files stolen out from under it will eventually notice, as it periodically re-checks the completion data for its save destination. When it notices data missing, it will update the completion map for the torrent to no longer consider those data blocks "complete".

It's advisable not to do anything that modifies the contents of a torrent's download location unless it's stopped or, preferably, removed from BiglyBT entirely. While the client is managing a torrent, the save directory is under its control and shouldn't be modified. (The files can be copied, played, etc... read-only access is fine. Just no changes/removals.)

If this is happening _without_ any modifications to the save directory, then I'm stumped. What does the completion status of the torrent's individual files look like, if you open the Files tab of the torrent details view? Is every file at less than 100%? Are they all at 0%? Or is only some of the data missing from some of the files?

**Comment by HJKaye** [comment] 2022-11-06 02:44
> When you say, the files are there, but no content do you mean the files are empty?

Yes, they show in the folder with the correct file size, but they are empty. Mostly videos and images, difficult to see if they are actually empty. I've opened a few in notepad, they look empty. VLC player attempts to play, then gives up, image viewers show invalid image message. They are also on the NAS where they should be after 'completion moving' finishes, in other words they're not in the default directory anymore but they are moved there by bigly.

> If so, was the data present BEFORE the torrent returned to incomplete status, to the best of your knowledge?

Yes, in many instances I've watched the videos and/or viewed the images. It's impossible to know if that's the case every time, but I'm absolutely certain there are many that were complete and useable. 

> if you open the Files tab of the torrent details view? Is every file at less than 100%? Are they all at 0%? Or is only some of the data missing from some of the files?

I checked the details screen on a few, individual files show less than 100% for the most part. For torrents that just reappeared on the incomplete list, all the individual files show 0% on the detail screen, as well as on the main incomplete torrents list. 

On the main incomplete torrents list, the 'done' percentage is zero when the torrent first shows up back on the list, as well as the individual files. The Downloaded column always shows equal to the size column at first, until it starts downloading again then it gradually increases, I've never watched it happen, but I presume the downloaded column will show exactly double the size and then it will end up on the completed list again.

> Or were the files previously moved/deleted from the download location?

I never touch the completed files, bigly is set to move completed files to my NAS via a mapped drive, and that's where they stay until I delete them via the bigly interface only. I do have had a nagging issue of the mapped drives occasionally dropping overnight, but that shouldn't cause this to happen so regularly and continuously unless it's a bug.

**Comment by ferdnyc** [comment] 2022-11-06 09:33
Mmm... still, it does _sound like_ something external is deleting the files (and/or their contents) out from under BiglyBT.

If output files are deleted for an active torrent, BiglyBT will (when it notices) recreate them as empty allocations, placeholders for the data to be stored as it's downloaded.

It does the same thing when preparing the output directory for a newly-started torrent. If you were to start and then immediately stop a torrent, you'd see exactly the same thing in its output directory: All of the enabled files created, but empty of any data (and [sparsely-allocated](https://en.wikipedia.org/wiki/Sparse_file), on filesystems that support it, to conserve disk space).

So, the fact that you're seeing _exactly_ that can't be a coincidence.

I suppose it's _possible_ that issues with the mapped network drive could cause that. If BiglyBT tries to check a file's contents and the read fails, it could be mistaking that for the file having been deleted or moved, and jumps the gun on zeroing out the completion/contents... but it seems odd that would happen to **all** files in a torrent, and it's also weird that it would hit read failures checking the files, but then have no problems _updating_ them to delete the contents. That'd be a pretty magical Heisenbug.

It really does feel like something _else_ is removing the files, though, at least from BiglyBT's perspective. Like I said, in that type of situation it would respond by doing EXACTLY what you're seeing: Recreate the missing files, but as empty download targets for it to fill with data as it's received. If BiglyBT were spontaneously doing that _all by itself_, for no reason... I'm certainly not claiming it's **impossible**, but if that were the case I'd expect at least _some_ other users reporting the same problem. So far there don't seem to be any. Which isn't to say that you're not actually experiencing a real issue, by any means. Just that the root cause of the behavior is still unclear.

You've checked for possible external causes for the files disappearing, I assume? You're not transferring them into a space on the NAS that auto-deletes files periodically or when the size exceeds a quota, anything like that? (Don't laugh -- I once had a user who was paranoid about never letting anyone empty his computer's Trash/Recycle Bin, because he "has files in there that he might still need". I just stared at him for like 20 seconds.)

**Comment by HJKaye** [comment] 2022-11-06 22:53
> Mmm... still, it does sound like something external is deleting the files (and/or their contents) out from under BiglyBT.

I don't disagree, but if that were the case, would bigly not reallocate the files in the default directory? 

- When this happens, the sparse files still show on the NAS. 
- The default directory is on my laptop, the completion moving target is my NAS. 
- I checked the creation date on a few, the creation date = modified date, which is, I presume, when the file was moved to the NAS.  
- Individual files on the torrent detail screen show _remaining_ column (pieces I presume) is blank.
- Info screen shows a _file completed_ date&time, _completed on_ is blank. Not sure what the difference is?
- Individual files on detail screen show _path=\_ (+appropriate sub-folders when present), for some, _correct NAS path_ for others.

> You've checked for possible external causes for the files disappearing, I assume? You're not transferring them into a space on the NAS that auto-deletes files periodically or when the size exceeds a quota, anything like that? 

Yes, I have. It seems to only affect torrent files. There are files in my download folder for software I don't even use anymore :) Yes, I must clean up. There's plenty of space (close to 500GB). 

_Question:_ Are there any log files that might give any clues on this?

**Comment by Menard01** [comment] 2023-04-28 14:15
I had this too with Deluge on Linux, many times with many torrents, I don't understand how it is possible, it is with torrents that were completed, and when I want to back up the files I do a recheck with Deluge, and then it appears that some files are not complete wit some 99% 98% 97% etc 80% then I resume the torrent and a download immediately starts with clearly a real data transfer by the internet.
But the main point is when checking the hash of the files they don't change ... but for that point I guess that it is caused by the preallocation of the files, I suppose a preallocated file has the same hash than the completed file , and though I didn't asked for preallocate files creation in the settings
In fact by now I cannot really tell that you must complete these file download to get all the data in it

**Closed** 2024-01-13 11:49 UTC
