### ISSUE TITLE
[Ubuntu 20.04] Crashes every time soon after startup

### ISSUE THREAD

**Issue by sklm** [BiglySoftware/BiglyBT#1641] opened 2020-05-13 14:07 UTC
Ubuntu 20.04 with all the latest updates.
KDE desktop.

Help->About:
Java 11.0.7 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4934r5, gtk/3.24.18, zoom=100, dpi=96
Linux v5.4.0-29-generic, amd64 (64 bit)
B2.4.0.0/4 az3

Last messages seen in console during the crash:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8c77c4a559, pid=25192, tid=25213
#
# JRE version: OpenJDK Runtime Environment (11.0.7+10) (build 11.0.7+10-post-Ubuntu-3ubuntu1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0x12559]  pthread_getcpuclockid+0x9
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /opt/BiglyBT/core.25192)
#
# An error report file with more information is saved as:
# /opt/BiglyBT/hs_err_pid25192.log
Compiled method (nm)  730788 7593     n 0       sun.management.ThreadImpl::getThreadTotalCpuTime0 (native)
 total in heap  [0x00007f8c607fbe10,0x00007f8c607fc1b0] = 928
 relocation     [0x00007f8c607fbf88,0x00007f8c607fbfb8] = 48
 main code      [0x00007f8c607fbfc0,0x00007f8c607fc1b0] = 496
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
#
./biglybt: line 251: 25192 Aborted                 (core dumped) ${JAVA_PROGRAM_DIR}java -Xmx256m -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Exit from BiglyBT complete
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/opt/BiglyBT/BiglyBT.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
No shutdown tasks to do
BiglyBT TERMINATED.

````

**Comment by parg** [comment] 2020-05-13 14:43
Can you try running with a different version of Java? That crash is within the JVM code itself.

**Comment by sklm** [comment] 2020-05-13 14:48
Originally I was on OpenJDK 14 and had the same issue. Also noticed that it was in JVM so I downgraded to OpenJDK 11 but to no avail.
I am going to try some other JDKs, e.g. Oracle's build, and report back.

**Comment by sklm** [comment] 2020-05-13 15:08
Same crash with Oracle Java 14:

Help->About:
Java 14.0.1 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-14-oracle

SWT v4934r5, gtk/3.24.18, zoom=100, dpi=96
Linux v5.4.0-29-generic, amd64 (64 bit)
B2.4.0.0/4 az3

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f93f002c559, pid=35734, tid=35756
#
# JRE version: Java(TM) SE Runtime Environment (14.0.1+7) (build 14.0.1+7)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0x12559]  pthread_getcpuclockid+0x9
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /opt/BiglyBT/core.35734)
#
# An error report file with more information is saved as:
# /opt/BiglyBT/hs_err_pid35734.log
Compiled method (n/a)   80735 7142     n 0       sun.management.ThreadImpl::getThreadTotalCpuTime0 (native)
 total in heap  [0x00007f93d85cc210,0x00007f93d85cc590] = 896
 relocation     [0x00007f93d85cc368,0x00007f93d85cc398] = 48
 main code      [0x00007f93d85cc3a0,0x00007f93d85cc590] = 496
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
./biglybt: line 251: 35734 Aborted                 (core dumped) ${JAVA_PROGRAM_DIR}java -Xmx256m -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Exit from BiglyBT complete
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava12 (file:/opt/BiglyBT/BiglyBT.jar) to field java.net.InetAddress.nameService
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava12
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
No shutdown tasks to do
BiglyBT TERMINATED.

```

**Comment by parg** [comment] 2020-05-13 15:11
Consistent crash location at least. Can you upload one of the hs_err_pid<nnnn>.log files referenced in your crash info (/opt/BiglyBT/hs_err_pid35734.log in the last one)

**Comment by sklm** [comment] 2020-05-13 15:15
Here. Hope this attachment works...

[hs_err_pid35734.log](https://github.com/BiglySoftware/BiglyBT/files/4622871/hs_err_pid35734.log)

**Comment by parg** [comment] 2020-05-13 15:57
Sounds a bit like https://bugs.openjdk.java.net/browse/JDK-8188695

**Comment by parg** [comment] 2020-05-13 16:09
The BiglyBT.jar is just a .zip file - can you remove the entry in the for file 'AEThreadMonitor' (path 'com.biglybt.core.util.jman') and see if that fixes things?

**Comment by sklm** [comment] 2020-05-13 16:36
So I removed these three classes from the jar:
AEThreadMonitor$1.class
AEThreadMonitor$2.class
AEThreadMonitor.class

Now it only has two remaining in that package:
com/biglybt/core/util/jman/AEMemoryMonitor$1.class
com/biglybt/core/util/jman/AEMemoryMonitor.class

But this didn't help much. I just got another crash
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd7a4b61559, pid=43266, tid=43289
#
# JRE version: Java(TM) SE Runtime Environment (14.0.1+7) (build 14.0.1+7)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0x12559]  pthread_getcpuclockid+0x9
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /opt/BiglyBT/core.43266)
#
# An error report file with more information is saved as:
# /opt/BiglyBT/hs_err_pid43266.log

[hs_err_pid43266.log](https://github.com/BiglySoftware/BiglyBT/files/4623334/hs_err_pid43266.log)

```

**Comment by parg** [comment] 2020-05-13 16:48
Odd, still seems those classes are there - check the error log file:


    j  com.biglybt.core.util.jman.AEThreadMonitor.monitor15()V+198
    j  com.biglybt.core.util.jman.AEThreadMonitor.access$0()V+0
    j  com.biglybt.core.util.jman.AEThreadMonitor$1.runSupport()V+6
    j  com.biglybt.core.util.AEThread.run()V+1

**Comment by sklm** [comment] 2020-05-13 17:08
Oh, I just noticed something... I had another really old leftover BiglyBT 1.6 jar hanging in the same folder, just next to the correct one. So the startup script has added it to CLASSPATH, too. This is likely where the old classes imported from.

So I removed the old jar and now testing again. If it doesn't crash then I am going to restore the AEThreadMonitor class bak and test some more with the complete original 2.4.0.0 jar. Right now it seems like the problem was somewhere between the keyboard and the chair :-)

**Comment by sklm** [comment] 2020-05-13 17:42
OK, done a clean install into an empty folder to ensure no old junk.

With the original jar, the same crash reproduces consistently.
With AEThreadMonitor classes removed from the jar, it seems to run smoothly so far.

Currently running,
```
Java 14.0.1 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-14-oracle

SWT v4934r5, gtk/3.24.18, zoom=100, dpi=96
Linux v5.4.0-29-generic, amd64 (64 bit)
B2.4.0.0/4 az3
```

**Comment by parg** [comment] 2020-05-13 17:49
OK, good to get you running! Unfortunately we're no nearer to figuring out why that crash is occurring on your system. Some combination of gcc 8.3.0 being used for Java and your pthread 2-31?

**Comment by sklm** [comment] 2020-05-13 17:57
I think Ubuntu has updated gcc just recently. Here is what I have at the moment

```
$ sudo apt list --installed | grep -Ei "gcc|java|jdk"

gcc-10-base/focal,now 10-20200411-0ubuntu1 amd64 [installed,automatic]
gcc-10-base/focal,now 10-20200411-0ubuntu1 i386 [installed,automatic]
gcc-9-base/focal,now 9.3.0-10ubuntu2 amd64 [installed,automatic]
gcc-9/focal,now 9.3.0-10ubuntu2 amd64 [installed,automatic]
gcc/focal,now 4:9.3.0-1ubuntu2 amd64 [installed,automatic]
java-common/focal,focal,now 0.72 all [installed,automatic]
javascript-common/focal,focal,now 11 all [installed,automatic]
libgcc-9-dev/focal,now 9.3.0-10ubuntu2 amd64 [installed,automatic]
libgcc-s1/focal,now 10-20200411-0ubuntu1 amd64 [installed,automatic]
libgcc-s1/focal,now 10-20200411-0ubuntu1 i386 [installed,automatic]
libgcc1/focal,now 1:10-20200411-0ubuntu1 amd64 [installed,automatic]
libjavascriptcoregtk-4.0-18/focal-updates,focal-security,now 2.28.2-0ubuntu0.20.04.1 amd64 [installed,automatic]
libjuh-java/focal-updates,focal-updates,now 1:6.4.3-0ubuntu0.20.04.1 all [installed,automatic]
libjurt-java/focal-updates,focal-updates,now 1:6.4.3-0ubuntu0.20.04.1 all [installed,automatic]
libridl-java/focal-updates,focal-updates,now 1:6.4.3-0ubuntu0.20.04.1 all [installed,automatic]
libuno-cppuhelpergcc3-3/focal-updates,now 1:6.4.3-0ubuntu0.20.04.1 amd64 [installed,automatic]
libuno-purpenvhelpergcc3-3/focal-updates,now 1:6.4.3-0ubuntu0.20.04.1 amd64 [installed,automatic]
libuno-salhelpergcc3-3/focal-updates,now 1:6.4.3-0ubuntu0.20.04.1 amd64 [installed,automatic]
libunoloader-java/focal-updates,focal-updates,now 1:6.4.3-0ubuntu0.20.04.1 all [installed,automatic]
oracle-java14-installer/focal,now 14.0.1-1~linuxuprising1 amd64 [installed]
oracle-java14-set-default/focal,now 14.0.1-1~linuxuprising1 amd64 [installed,automatic]

```

**Comment by parg** [comment] 2020-05-13 19:35
I'm seeing other issues with 11.0.7 on kubuntu - general view doesn't load, for example, and the close-down progress dialog doesn't show. Seems to be something to do with native libraries not loading but not sure what :( Works fine with Java 8

**Comment by sklm** [comment] 2020-05-13 21:56
In my case the original 2.4.0.0 jar crashes even with openjdk 1.8

```
Java 1.8.0_252 (64 bit)
  Private Build
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4934r5, gtk/3.24.18, zoom=100, dpi=96
Linux v5.4.0-29-generic, amd64 (64 bit)
B2.4.0.0/4 az3
```

On the other hand, jar with removed AEThreadMonitor works fine. So to recap, the original complete jar crashes on all versions of java; while the trimmed one works fine on all java versions.

**Comment by sklm** [comment] 2020-05-13 22:12
Not to hijack my own thread, but is it a known issue that the tag items counter at the top toolbar always shows "0 times: 0 active", even when there are some torrents in this tag, including some active?

Note that the numeric labels next to the tags on the sidebar show correct values. Also, the Tag Overview panel has the right numbers too. So it's only wrong in the toolbar's counter.

<img width="1614" alt="BB_tags" src="https://user-images.githubusercontent.com/7455864/81871026-0c4ee300-9545-11ea-887d-4aa59581b67d.png">

**Comment by parg** [comment] 2020-05-14 07:44
Looks like a Linux-only issue, I'll take a look

**Comment by parg** [comment] 2020-05-14 13:27
Fixed in 2401_B02 when built

**Comment by sklm** [comment] 2020-05-14 20:00
Thank you very much. In the meantime, jar 2.4.0.0 with removed AEThreadMonitor has been running rock solid for the past 24hr.

**Comment by parg** [comment] 2020-05-15 15:05
Next beta will have a system property to disable thread monitoring - run with

`-Dbiglybt.thread.monitor.enable=0`

Better than having to remove the class file but obviously not as good as knowing what the cause of this is!

**Comment by sklm** [comment] 2020-05-16 06:33
Thanks for the workaround. In the default configuration it crashed very quickly, with the same diagnostics. After adding the new property it seems to be running just fine.

Also thanks for fixing the indicator for number of items in a tag, it is now showing correctly again.

**Comment by parg** [comment] 2020-05-26 08:22
Opened https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8245768

**Closed** 2024-01-13 12:04 UTC
