### ISSUE TITLE
Torrent Confirmation Window Doesn't *ALWAYS* Remember its Correct Position

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1261] opened 2019-09-21 00:51 UTC
The window seems to remember its size and mostly it's last position but sometimes it just moves.  I have seen this mostly when it may contain more than one torrent's info but that could just be as more activity is happening in that timeframe.  I have lots of Windows on the screen and I like things positioned for ease of access.  

The monitor configuration hasn't changed and it could be seconds from the last correctly placed window to it moving.

Java 1.8.0_201 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_201

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.0/4 az2

**Comment by parg** [comment] 2019-09-22 14:04
Seems consistent to me - see if you can find a way of reliably reproducing it please.

**Comment by dbareis** [comment] 2019-09-24 02:14
It's inconsistent, is there any logging I can turn on? Or any apps to monitor the windows?

**Comment by parg** [comment] 2019-09-24 09:14
I found something that might be the cause of your bug, fixed in next beta (B07) - thanks !

**Comment by dbareis** [comment] 2019-11-17 21:44
I haven't seen this in the latest betas.

**Closed** 2024-01-13 12:05 UTC
