### ISSUE TITLE
I/O Exception while downloading 'https://plugins.biglybt.com/update/pluginlist3.php', Connect timed out

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1062] opened 2019-05-14 06:11 UTC
started a week or 2 ago, the automated update check would always fail. I haven't done any config change or update (at least not manually). access to https://plugins.biglybt.com/update/pluginlist3.php in browser looks fine, so not sure why it's not working for Bigly while Torrents also work just fine

```
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_181

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.0/4 az3
```
```
Checking for Updates - added
Checking for Updates
    Core Patch Checker -     Adding update: Core Patch Checker
    Core Patch Checker - Finished
    SWT library -     SWT: current version = 4922, latest version = 4508
    SWT library - Finished
    BiglyBT Core -     Core: latest_version = '1.9.0.0', file = 'http://version.biglybt.com/biglybt-files/core/BiglyBT_Update_1.9.0.0_win64.zip.torrent'
    BiglyBT Core - Finished
    Platform-specific support -     Failed to load plugin details for the platform manager: Plugin list load failed, https://10.138.191.181/update/pluginlist3.php?type=&&version=1.9.0.0&&app=BiglyBT&&os=Windows+10&&osv=10.0&&arch=amd64&&ui=az3&&java=1.8.0_181&&swt_platform=win32&&swt_version=4922&&pmv=1.27&&epids=azlocprov%3Aaercm%3Aazmsgsync%3Aazneti2phelper%3Aazutp%3Amlab%3Amldht%3Aaznettor%3A: I/O Exception while downloading 'https://plugins.biglybt.com/update/pluginlist3.php', Connect timed out
    Platform-specific support - Failed
Failed
    Mandatory plugins -     Failed to load plugin details: Plugin list load failed, Proxy not available
    Mandatory plugins - Failed
Failed
    Non-mandatory plugins -     Failed to load plugin details: Plugin list load failed, Proxy not available
    Non-mandatory plugins - Failed
Finished
```

**Comment by parg** [comment] 2019-05-14 08:06
Do you have 'update anonymously' enabled in your BiglyBT config? If so then try disabling that and see if things work.

FYI the reference to 10.138.191.181 in that log is BiglyBT trying to route the update check over Tor - normally this is done only if a plain connection fails but if you have enabled anonymous updates then it always does this.

**Comment by SUCM** [comment] 2019-05-14 15:02
update anonymously has been enabled for a long long time, but update check has been running without problem for months until a week or 2 ago. did some plugin update changed the behaviour?

**Comment by parg** [comment] 2019-05-14 16:21
nothing has changed that I know of :(

**Comment by SUCM** [comment] 2019-05-15 03:40
I disabled update anonymously for now. will see in the next 12 hours. I have been removing successfully update check for months now, so not sure why it started to fail within the last 13 days

**Comment by SUCM** [comment] 2019-05-15 07:40
maybe server is acting up?
'''
https://10.89.161.243/update/pluginlist3.php?type=&&version=1.9.0.0&&app=BiglyBT&&os=Windows+10&&osv=10.0&&arch=amd64&&ui=az3&&java=1.8.0_181&&swt_platform=win32&&swt_version=4922&&pmv=1.27&&epids=azlocprov%3Aaercm%3Aazmsgsync%3Aazneti2phelper%3Aazutp%3Amlab%3Amldht%3Aaznettor%3A: I/O Exception while downloading 'https://plugins.biglybt.com/update/pluginlist3.php', Malformed reply from SOCKS server
    Platform-specific support - Failed
Failed
'''

**Comment by SUCM** [comment] 2019-06-06 04:40
looks like it just fixed itself today

    Checking for Updates - added
    Checking for Updates
        Core Patch Checker -     Adding update: Core Patch Checker
        Core Patch Checker - Finished
        BiglyBT Core -     Core: latest_version = '2.0.0.0', file = 'http://version.biglybt.com/biglybt-files/core/BiglyBT_Update_2.0.0.0_win64.zip.torrent'
        SWT library -     SWT: current version = 4922, latest version = 4508
        SWT library - Finished
        BiglyBT Core -     Adding update: Core BiglyBT Version
        BiglyBT Core - Finished
        Platform-specific support -     Win32: current = 1.27, latest = 1.27
        Platform-specific support - Finished
        Non-mandatory plugins -     Loading details for azlocprov/Location Provider
        Mandatory plugins -     Loading details for azupdater/BiglyBT Update Support
        Non-mandatory plugins -     Plugin: azlocprovversions (current=0.3.9, latest=0.4.0)
        Mandatory plugins -     Plugin: azupdaterversions (current=2.1, latest=2.1)
        Mandatory plugins - Finished
        Non-mandatory plugins -     Plugin is unloadable
        Non-mandatory plugins -     Adding update: azlocprov/Location Provider
        Non-mandatory plugins -     Loading details for aercm/Swarm Discoveries
        Non-mandatory plugins -     Plugin: aercmversions (current=0.6.15, latest=0.6.15)
        Non-mandatory plugins -     Loading details for azmsgsync/Message Sync Support
        Non-mandatory plugins -     Plugin: azmsgsyncversions (current=0.8.8, latest=0.8.8)
        Non-mandatory plugins -     Loading details for azneti2phelper/I2P Helper Plugin
        Non-mandatory plugins -     Plugin: azneti2phelperversions (current=0.9.39.2.1, latest=0.9.40.1.1)
        Non-mandatory plugins -     Plugin is unloadable
        Non-mandatory plugins -     Adding update: azneti2phelper/I2P Helper Plugin
        Non-mandatory plugins -     Loading details for azutp/uTP Plugin
        Non-mandatory plugins -     Plugin: azutpversions (current=0.6.3, latest=0.6.3)
        Non-mandatory plugins -     Loading details for mlab/Measurement Lab (M-Lab)
        Non-mandatory plugins -     Plugin: mlabversions (current=0.3, latest=0.3)
        Non-mandatory plugins -     Loading details for mldht/mlDHT
        Non-mandatory plugins -     Plugin: mldhtversions (current=2.2.5, latest=2.2.5)
        Non-mandatory plugins -     Loading details for azplatform2/Platform-Specific Support
        Non-mandatory plugins -     Plugin: azplatform2versions (current=1.27, latest=1.27)
        Non-mandatory plugins -     Loading details for aznettor/Tor Helper Plugin
        Non-mandatory plugins -     Plugin: aznettorversions (current=1.2.4, latest=1.2.4)
        Non-mandatory plugins - Finished
    Finished

**Comment by SUCM** [comment] 2019-06-06 04:40
was still failing less than 8 hours ago though

**Comment by ferdnyc** [comment] 2022-11-06 01:05
I still hit this sometimes when my not-particularly-high-end D-Link router gets oversaturated with UDP connections. (BiglyBT is often both the cause and the victim, in those instances.)

AFAICT the router maintains a table of active NAT traversals, and that list can grow too large/full under heavy load. When it's too full/big, the router goes into this mode where requests to external HTTPS URLs will start lagging heavily or even timing out... _seemingly_ for no reason. It's always a local network problem, and rebooting the router always fixes it for me, though left to its own devices the problem can also clear up on its own.<sup>1</sup>

#### Notes
1. The fact that the problem is self-correcting over time reinforces my suspicion that it's the NAT traversals. All ports, even UDP ports, have a session entry on the table, and every entry has an expiration timeout. I suppose they've implemented a sort of poor-man's (TCP) `TIME_WAIT`, but for all protocols including UDP. Since UDP is connectionless, there are no well-defined "session" boundaries, so the router adds a session entry every time it receives data on a new port combination, and it treats every subsequent datagram as the closing packet of an implicit session that then begins counting down to its removal from the table.
    
    Those timeouts make UDP traffic much heavier than normal -- heavier than TCP, in fact, because the session entry for a TCP connection that closes gracefully and completely doesn't need to hang around. But when a torrent-client-sized barrage of brief UDP transactions, each exchanging only a few bytes, stuffs dozens or hundreds of new rows into that session table, they will be there for a very long time. (The UDP session timeout is 300 seconds, best I can determine.) But eventually the table shrinks back down to a size the router can handle, and then HTTPS stops being flaky.

**Closed** 2024-01-13 12:06 UTC
Labels: enhancement
