### ISSUE TITLE
freeze/hang forever in torrent's Files tab

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#927] opened 2019-03-14 04:47 UTC
Java 1.8.0_181 (64 bit)
Oracle Corporation
c:\program files\java\jre1.8.0_181

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.8.0.0/4 az3

when viewing Files tab of a Torrent, BiglyBT would freeze/hang forever. after multiple experiment, I think BiglyBT is stuck when the view needs to display files with system file type icon from Alcohol 120%

attached is FileTypesMan's info on this file type

**Comment by SUCM** [comment] 2019-03-14 04:51
since attachment failed. here is the image
![Image of Yaktocat](https://i.imgur.com/G6FTrFq.png)

**Comment by parg** [comment] 2019-03-14 12:13
Can you reproduce the hang and then go to a browser and enter

http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;

(make sure you include the double ;; at the end of that)

If this 'page' loads then upload the debug_1.log / debug_2.log as this should contain some stack traces that might pinpoint the issue - these are in the 'logs' directory of the BiglyBT config folder (%appdata%\BiglyBT on Windows)

**Comment by SUCM** [comment] 2019-03-15 07:31
page loads as setinfo.dib that firefox says is a 20x20 bmp picture displaying as the placeholder of online picture with invalid URL

**Comment by SUCM** [comment] 2019-03-15 07:39
looks like it only loads page as as setinfo.dib for the first couple seconds of freeze, then the page just goes into forever loading but doesn't timeout after 10 minutes in that loading state

I checked and confirmed that page also loads as setinfo.dib when BiglyBT is not in freeze/hang state


this means page is not loadable in freezing state, but als not loading as any page when working properly

**Comment by parg** [comment] 2019-03-15 08:58
Can you check the same problem occurs with the latest beta? Go to the Help menu for details.

**Comment by SUCM** [comment] 2019-03-15 17:15
exact same thing with the latest beta b30

**Comment by parg** [comment] 2019-03-15 17:23
And if you disable the columns that show an icon (name, fullname) (right-click on the column header area and uncheck those columns) you don't get any issues at all?

No other users have reported this kind of problem so I am struggling to see how an icon of a particular type could cause an issue.

**Comment by SUCM** [comment] 2019-03-15 17:29
yes, disable Name column (which displays file type system icons) allows me to scroll and view the whole Files tab without freeze. it's how I arrived at the conclusion of this issue report

searching online, there are other users on Alcohol's forum reporting similar issue with various software as well. another Java program JD2 had a thread with the exact same issue too

**Comment by parg** [comment] 2019-03-15 17:36
Sounds like an Alcohol issue then...

**Comment by SUCM** [comment] 2019-03-15 17:52
Alcohol's issue for not system icon config, but BiglyBT and other software's issue on freezing?

**Comment by SUCM** [comment] 2019-03-15 17:53
for example, uTorrent simply display unknown file icon and move on. doesn't freeze/stall at all

**Comment by SUCM** [comment] 2019-03-15 17:56
other programs like 7zip and FreeFileSync display correct icon without issue

**Comment by parg** [comment] 2019-03-15 17:59
OK, I'll change BiglyBT to ignore.cue file icons - will that do it?

**Comment by parg** [comment] 2019-03-15 18:04
Over the years I've wasted enough of my time trying to work around Alcohol software issues, just in case you wondered.

**Comment by SUCM** [comment] 2019-03-16 04:21
Alcohol isn't the only software I had encountered this type of issue. forgot the other two which I don't use anymore. is it possible to put a timeout on displaying icon (not sure the mechanism Bigly uses to display system icon) to just give up after a small try similar to uTorrent's handling if what 7zip and FreeFileSync do are not possible?

I'm guessing the freezes is due to no timeout on the wait which blocks the threads indefinitely. an option to list all file types with potential problematic icons would be the last resort if we exhausted all other options

**Comment by parg** [comment] 2019-03-16 09:14
I'm guessing the problem is caused by Alcohol injecting some crap software into the BiglyBT process to try and intercept interactions with .cue files and that there is something in the way that the Java runtime/SWT runtime/who knows what that causes Alcohol to screw up the process.

I can't add a timeout to that logic flow. I could possibly change the way that BiglyBT attempts to get icons for .cue files although not sure that would help. I'll hack something together for you to test in the next beta.

**Comment by SUCM** [comment] 2019-03-16 09:18
JD2's workaround was for user to put down one dummy icon for each file type in its icon repository folder since it only tries to grab icon from system if icon is not already in its repository folder. I don't know if Bigly does the same thing or not

**Comment by parg** [comment] 2019-03-16 09:29
Not really a solution if it requires the user to recognise the problem and manually extract and copy icon files?

**Comment by SUCM** [comment] 2019-03-16 09:35
I would prefer to designate a special icon (maybe the Bigly icon) for a list of file types if Bigly intercepting the icon obtaining process is not possible since Alcohol takes a couple file types, not just cue

**Comment by parg** [comment] 2019-03-16 10:22
Can you test with the latest beta, B31, to see if the problem remains. I switched the icon loading code but I wouldn't be surprised if it still crashes as it isn't that different...

**Comment by SUCM** [comment] 2019-03-16 11:11
B31 doesn't crash, it just displays no icon for the cue file

**Comment by SUCM** [comment] 2019-03-16 11:12
I mean, no freeze/hang. hopefully it wasn't hardcoding, but more of a general handling

**Comment by SUCM** [comment] 2019-03-16 11:22
surprisingly, it freeze/hang on ISO/IMG files (still Alcohol file type icons), but displays ISO icon properly on relaunch. just not IMG

seems better, just not completely resolved

**Comment by parg** [comment] 2019-03-16 11:42
Meh. Give me a full list of Alcohol file type icons and I'll manually exclude them from being loaded.

**Comment by SUCM** [comment] 2019-03-16 11:53
I had tries all Alcohol file types. only ISO and IMG froze with B31. their System Type Name are Windows.IsoFile, not AlcoholImageFile. wonder if that made the difference on whatever caused the freeze

**Comment by parg** [comment] 2019-03-16 21:54
Try B32. There is an option under Tools->Options->Interface->Display to add your own extensions to be ignored for icons. It should pick up .cue etc as defaults, tell me if it doesn't

**Comment by SUCM** [comment] 2019-03-17 01:21
B32 default is empty list and freezes on cue file. I added cue to the list after relaunch, then it doesn't freeze anymore

**Comment by parg** [comment] 2019-03-17 07:04
darn it, I was testing for the presence of 'AxShlex.dll' as this used to be an indicator that Alcohol was loaded. Any way you can find out an Alcohol related DLL that is loaded into the BiglyBT process?

**Comment by SUCM** [comment] 2019-03-17 07:16
since I'm on 64-bit system, Bigly has AxShlEx64.dll loaded when frozen. it's not loaded when not frozen

**Comment by SUCM** [comment] 2019-03-17 07:25
I think Alcohol tries to dynamically add options to right click context menu (to insert image to virtual drive) since it doesn't present its menu when unregistered and only present right click context menu when registered all without reboot/restart. this is probably the reason why it's injecting that DLL

the file types icons display doesn't depend on Alcohol's registration status and are in AxShlRes.dll, so I'm guessing the injection is just side effect of menu, not because it's using Alcohol's file types icon

**Comment by parg** [comment] 2019-03-18 13:06
I reworked things a bit - please test B33. It will reset the ignore-icons and hopefully fill them with a larger set of Alcohol related ones.

**Comment by SUCM** [comment] 2019-03-21 04:36
B34 still freezes. need that explicit list added with B32

**Comment by SUCM** [comment] 2019-03-21 04:39
not sure if your list is correct, but I populated list with cue;iso;img;mds;mdf during my test to avoid freeze. the committed code adds .img;.mds;.iso;.bwt;.b5t;.b6t;.ccd with extra dot for all extensions

**Comment by parg** [comment] 2019-03-21 10:13
Did you run B33? That version should have auto-populated the list with the list I committed. B34 didn't do that so if you skipped B33 you messed up my test.

**Comment by SUCM** [comment] 2019-03-21 16:45
B34 was offered on restart of B33 update, so I let it went for B34 without thinking too much and straight tested B34 thinking B34 kept the change

**Comment by parg** [comment] 2019-03-21 16:59
So did you run B33 at all? B33 cleared the value set for the icon ignore config and should have re-populated with default with the Alcohol extensions if it detected Alcohol. If you ran B33 and it cleared the icons and didn't re-populate it then detection failed. FYI detection is based on

1) presence of the AxShlEx64.dll DLL in process
or
2) detection of a folder based on BiglyBT install location 'x'
    x\..\Alcohol Soft
    x\.. (+ or - x64)\Alcohol Soft

So typically

C:\Program Files\Alcohol Soft
C:\Program Files (x86)\Alcohol Soft

**Comment by parg** [comment] 2019-03-21 18:46
I'll try again in B35. B35 will reset that config parameter again, please report.

**Comment by SUCM** [comment] 2019-03-22 04:42
I think detection worked on B35. my list got replaced with the list in your code

**Comment by SUCM** [comment] 2019-03-22 04:44
and no freeze. Bigly immediately freeze whenever I tried cleared the list manually

**Comment by parg** [comment] 2019-03-22 08:45
good!

**Closed** 2019-12-16 11:03 UTC
