### ISSUE TITLE
"Delete" priority does not delete files

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1682] opened 2020-06-16 04:18 UTC
(BiglyBT Beta (2.4.0.1_B10) but this has been going on forever. Windows 10 Pro.)

I was looking at #1673 - geez that guy was salty - anyway, I don't believe "Delete" works the way you say there, at least with files matching the "Ignore" settings in the Files options page - if you set certain extensions to "auto-skip" or use the regular expression option (_great option_ by the way!) - then the priority is "Delete" but after the torrent is completed (and moved) the files are still present (with the `.!ut` extension, I'm using that option too - add suffix to incomplete files - if it makes a difference).

(It's somewhat annoying especially if I have auto-skipped in this way all of the files in a subdirectory - in that case the files and the directory are still present after the move and have to be deleted manually.)

(And another reason it is annoying is if you have a torrent that has a "canned" file - like "downloaded from foo.txt" or "get additional information here.txt" that you have set to auto-skip - and you would _like_ to "remove top level directory" so that the files from that torrent actually end up (after moving) in the proper destination directory instead of a subdir, then _not_ actually deleting (and not moving) these extra skipped-but-not-actually-deleted files cause conflicts with other finished torrents with that same file.  In fact, I'm pretty sure it causes conflicts while the torrent is still actively downloading too but I haven't tried it in ages.)

**Comment by Knocks** [comment] 2020-09-30 12:53
Salty guy from the original discussion here. 😂  Confirming the issue persists in 2.5.0.0.

Removing the checkmark from the download box does correctly mark the file with "Delete" priority now, but that doesn't prevent the file from actually getting downloaded.

Also confirming that it causes conflicts in situations where 3 torrents all have readme.txt, you select not to download it to avoid a conflict, but it gets created anyway.  The second and third torrent then conflict out and refuse to start because a readme.txt already exists.

**Comment by parg** [comment] 2020-09-30 13:14
That's why for multi-file torrents you select the default save behaviour which is to create a separate folder for the torrent (based on torrent name) and place the multiple files in that folder.

**Comment by Knocks** [comment] 2020-09-30 13:32
I agree that separate folders are a good way to handle downloads.  The issue remains though that "delete" priority files are still downloaded in the current build.

**Comment by david-bakin** [comment] 2020-09-30 13:48
The reason this behavior is "interesting" is that there are plenty of multi-file torrents that, when you clear out the cruft like "torrent downloaded from ..." (with regex filters, woohoo!) you're left with a single file.  For which it would be nice if you could just place it in the directory you want, rather than one named after the torrent.  (But you can also do it _after_ biglybt is done with it with scripts, which is what I do.)

**Comment by parg** [comment] 2020-09-30 14:06
The data for 'delete'/'dnd' files that corresponds to torrent files that overlap the start/end of the file HAS to be downloaded and stored somewhere - without these chunks the pieces can't be verified and therefore the end of the previous file/start of the next file can't be marked as downloaded. This data must be stored somewhere sensible to allow torrents to be archived and restored - if the data was stored in some temporary hidden location then this would bork things.

If you're that bothered about these partial files then either 1) configure BiglyBT to automatically add a suffix to such files so you can differentiate them or 2) configure BiglyBT to put them into a separate folder within the download.

**Comment by Knocks** [comment] 2020-10-02 13:10
To add to @david-bakin's post above, sometimes eager releasers will include .exe files in movie torrents, which is presumably not something you want on your PC at all, with a suffix or otherwise.  In uTorrent, I just unmarked everything except the main movie, and the problem was solved.  I'll have to look into regex filters, but that sounds that like it might open another can of worms.

**Comment by parg** [comment] 2020-10-02 13:18
Like I said, add a 'do not download' suffix to the files, that way the (most likely partial) file will be called 'whatever.exe.dnd'

**Comment by david-bakin** [comment] 2020-10-06 00:13
BTW the suggestion "configure BiglyBT to put them into a separate folder within the download" works great, I didn't know about it.

**Comment by parg** [comment] 2020-10-06 08:31
\o/

**Comment by krambra** [comment] 2021-01-03 18:22
"Do not download" suffix doesn't stop them from downloading.

**Comment by freMea** [comment] 2021-04-18 18:11
App version | OS 
------------------ | ---- 
2.7.0.2  | Win 10 x64 pro (french) 1909

Can someone explain to me why the unmark files (hence has priority as "delete") are not deleted when some are downloaded ? I don’t understand.

## Steps to reproduce

1. A torrent with lots of files in lots of directories and subdirectories
2. Only mark some files then start
3. The download begins and some "delete" files are downloaded (I know there is nothing wrong with this)

## Results

When the download is completed, those "delete" downloaded files are moved along the other completed ones (the ones I only want to keep) as if I mark them to download.

## Here are my settings
### Options/Files
![image](https://user-images.githubusercontent.com/22337329/115155559-ded9b600-a080-11eb-910c-117f46923047.png)
![image](https://user-images.githubusercontent.com/22337329/115155584-fa44c100-a080-11eb-8315-d6a3b28b5ff7.png)
![image](https://user-images.githubusercontent.com/22337329/115155601-0af53700-a081-11eb-89e5-2092326591cb.png)

## Expectations

I expect those "delete" downloaded files be deleted when the download is completed or at least the torrent is removed from the queue. Or be placed in a **.dnd_az!** subfolder as specified in settings.

**Why this doesn’t happen ? Can this be solved by fixing my setting ?**

**Comment by parg** [comment] 2023-09-05 10:33
There is the "export data and torrent files" menu option if you right-click on a download and select the Content menu tab.

This won't export partial files. It does result in everything being copied though.

**Comment by parg** [comment] 2023-09-05 13:57
Oh, actually there's this option:

Options->Files: When removing a download from the library delete any partial files for those selected as 'do not download' or 'delete'

So you would need to "remove from library" when removing the download, obviously not "delete from computer"

**Closed** 2024-01-13 12:04 UTC
