### ISSUE TITLE
BiglyBT crashes when switching desktop session on Windows 10

### ISSUE THREAD

**Issue by magsom** [BiglySoftware/BiglyBT#1320] opened 2019-10-29 05:18 UTC
Bug reproduce steps:
1. Login from local session, open BiglyBT.
2. Wait several minutes.
3. Login from remote desktop session, it crashes.

Error message:
```
Exception Processing Message 0xc0000005 Parameters
0x7ffd04a24e38 0x7ffd04a24e38 0x7ffd04a24e38 0x7ffd04a24e38
```

System info:
Java 12 (64 bit)  Oracle Corporation
SWT v4922r17, win32, zoom=200, dpi=144
Windows 10 18990, amd64 (64 bit)
B2.1.0.1_B11/4 az3

**Comment by parg** [comment] 2019-10-30 09:06
Is there a full crash-log for that? I can't reproduce it but I am using a virtual machine so not sure if that would make a difference.

**Comment by magsom** [comment] 2019-10-31 07:08
I didn't find any logs that close to crash time.

**Comment by magsom** [comment] 2019-11-01 08:36
This bug also happens occasionally when I close a chat window without switching desktop session.

**Comment by parg** [comment] 2019-11-11 08:34
Here's some input from the BiglyBT beta chat - chat:?BiglyBT%3A%20Beta%3A%20Chat

[02:08] Droo
Parg. In response to Mr Magsom of GitHub (Issue 1320).  He is likely running an older machine. Windows versions since 1903 (OP is running “2003” beta) have deprecated the use of the XDDM display driver in RDP (in favor of WDDM).
This causes many issues on older machines (that I have personally experienced) - black screen, high CPU usage and yes, intermittent crashing of BBT when starting RDP or closing chat boxes. The issue is outdated OEM display drivers which, in most cases, will never be fixed.
[02:09] Droo
The workaround is to disable the WDDM driver in gpedit: 
Computer Configuration->Policies->Windows Settings->Administrative Templates->Windows Components->Remote Desktop Services->Remote Desktop Session Host->Remote Session Environment>Use WDDM graphics display driver for Remote Desktop Connection
… and all the problems are gone.

**Comment by tvasenin** [comment] 2019-11-28 15:48
Recently, I've started getting BiglyBT crashes almost each time I connect via RDP to Win10 host (1809).

Stack trace is the same reported as "Crash 2" in https://bugs.eclipse.org/bugs/show_bug.cgi?id=543747#c120 :
```
msctf.dll!CInputContext::_DoEditSession
msctf.dll!CInputContext::_EditSessionQiCallback
msctf.dll!CInputContext::OnLockGranted
msctf.dll!CACPWrap::OnLockGranted
msctf.dll!CBackingStore::RequestLock
msctf.dll!CInputContext::_QueueItem
msctf.dll!CInputContext::RequestEditSession
msctf.dll!CCompositeContextAdapter::RequestEditSession
msctf.dll!CInputContextAdapter::_ExecuteOperation
msctf.dll!CInputContextAdapter::GetSelection
TextInputFramework.dll!CTextInputClientOwnerAsync::GetSelectionAsync
TextInputFramework.dll!TextInputClient::RegisterEditControl
TextInputFramework.dll!TextInputClient::OnProxyCreated
TextInputFramework.dll!CTextInputClientFreeThread::OnProxyCreated
TextInputFramework.dll!MessageProxyReconnectAdapter::CreateRemoteProxy
TextInputFramework.dll!MessageProxyReconnectAdapter::AttemptPullProxy
TextInputFramework.dll!MessageProxyReconnectAdapter::s_AttemptPullProxy
CoreMessaging.dll!Microsoft__CoreUI__Dispatch__TimeoutHandler$CallbackThunk
CoreMessaging.dll!Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch
CoreMessaging.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop
CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch
CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter_DoWork
CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc
user32.dll!UserCallWinProcCheckWow
user32.dll!DispatchMessageWorker
```

**Closed** 2024-01-13 12:05 UTC
