### ISSUE TITLE
Unlimited download speed not selectable

### ISSUE THREAD

**Issue by Gunni** [BiglySoftware/BiglyBT#79] opened 2017-10-03 22:16 UTC
I just noticed speed limit is active.

I have a gigabit connection. I want to use it.

![2017-10-03 22_12_34-new issue biglysoftware_biglybt](https://user-images.githubusercontent.com/358099/31151689-20f5edd2-a888-11e7-99aa-b5f79d8b48ab.png)

Windows 10 x64
BiglyBT B1.0.0.0/4 az3

**Comment by Gunni** [comment] 2017-10-03 22:21
Tried upgrading, didn´t work, going back to Tixati.

**Comment by parg** [comment] 2017-10-04 07:54
It doesn't look like the 'unlimited' option is disabled - what happens when you select it? Does it revert back to a limited value? I assume you haven' installed the speed scheduler plugin, or configured the built-in speed limiter?

**Comment by Gunni** [comment] 2017-10-04 10:03
It lets me click it, but acts as if i did not.

The selected speedlimit is applied, but i cannot increase it, even the ones i manage to select, are ignored.

**Comment by parg** [comment] 2017-10-04 11:53
Odd indeed. Of course, just because you are on a Gb LAN it doesn't mean you will be able to download at that rate, the rate you achieve is based on how fast other peers are uploading to you. That being said, I wouldn't expect it to stick at what looks like a limit. Depending on the download I can get speeds of 50Mbit/sec so it definitely isn't some hard limit in BiglyBT. 

There are some advanced settings under Tools->Options->Connection->Advanced Network Settings that you can fiddle with if you want (although I haven't changed them from defaults) - 'read select timeout' could be reduced to, say, 10, to see if that makes a difference.

**Comment by Gunni** [comment] 2017-10-04 16:33
I was downloading from another peer on the same lan, after i switched to Tixati it went fine at pretty much max connection speed.

**Comment by TuxPaper** [comment] 2019-06-23 19:18
Can't reproduce and since the user has switched clients, I shall close this and hope no one else has this problem!

**Closed by TuxPaper** 2019-06-23 19:18 UTC
