### ISSUE TITLE
BiglyBT freezes and hangs up when interacting with the GUI interface

### ISSUE THREAD

**Issue by LovelyBloom** [BiglySoftware/BiglyBT#2398] opened 2022-01-09 15:33 UTC
Hi, right now I'm on fedora, and before I was on ubuntu-mate so it's not the system (read further).
because of all the freezes and hangs up I downgraded to 1.6 and had no problem and the app automatically updated itself and there was no problem BUT after the update BiglyBT downloaded this package: swt_swt-4942r22-gtk-linux-x86_64.zip
after the update and restart freezes and hangs up came back could you look into this, please? It's obviously a problem with legacy swt and/or gtk

**Comment by parg** [comment] 2022-01-09 16:21
Try grabbing the latest SWT from 

https://download.eclipse.org/eclipse/downloads/drops4/S-4.23M1-202201051800/#SWT

and see if that helps. Grab swt-4.23M1-gtk-linux-x86_64.zip, unzip  it and replace the "swt.jar".

When running check the BiglyBT "About" dialog to verify you have updated correctly.

**Comment by mohsentux** [comment] 2022-01-09 22:50
thank you for the link. I tried it and it seems to be working. but I'm still on the fence. if something were to happen again I'll reply

thanx, mohsentux

**Comment by mohsentux** [comment] 2022-01-10 00:37
I'm trying my best to find legacy swt.jar file versions. but eclipse is jungle and I don't know how to navigate through it.
I've already tried all the versions that were available at the link with no success, where does eclipse keeps its old swt.jar files?

**Comment by mohsentux** [comment] 2022-01-10 01:11
I'm trying to see if this error is also on BiglyBT's standalone Jar file from github, but I don't know how to run it:
`java -jar GitHub_BiglyBT.jar
Error: Unable to initialize main class com.biglybt.ui.Main
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException`

**Comment by parg** [comment] 2022-01-10 09:03
That's just a warning that I know about - it doesn't cause any issues itself.

You can't just run that jar by itself - you need to rename it to BiglyBT.jar and replace the file in installation folder with it. That .jar is exactly the same as the one in the release's installers though.

**Comment by mohsentux** [comment] 2022-01-18 07:43
I believe the only way to fix crashes is using process of elimination
if I select a torrent in downloads nothing happens but let's say I have 15 downloads if I select the fifth torrent and hold shift and click on the tenth torrent It'll crash.
does this help narrow it down?

**Comment by parg** [comment] 2022-01-18 09:57
The issue(s) only occur on Linux - OSX/Windows don't have these kind of bugs. 

It doesn't happen on all types/window managers/versions of Linux.

My Kubuntu VM for example exhibits no issues.

The problem isn't with BiglyBT code, it is with either SWT or GTK.

So it is really rather hard to diagnose.

**Comment by parg** [comment] 2022-01-18 09:59
(oh, and Eclipse, the organisation responsible for SWT, do not seem very interested in fixing stuff)

**Comment by mohsentux** [comment] 2022-01-20 03:08
unless we experiment by defining everything as a constant and gtk or swt as the variable, we can't be sure that, that's causing the issue. I'll download the kde plasma for my fedora 35 and test it again.

**Comment by mohsentux** [comment] 2022-01-22 01:35
I tracked down the problem to this file: 

`swt_swt-4942r22-gtk-linux-x86_64.zip`

I installed the kde environment (didn't help with the bug). started an old version of biglybt so it would auto-update, after updating to 2.9 it was fine after restart then started downloading this file : `swt_swt-4922-gtk-linux-x86_64.zip` required restart and after that it still was fine but then it started downloading `swt_swt-4942r22-gtk-linux-x86_64.zip` after a restart bug reappeared.

so where do we go from here?
where is `swt_swt-4942r22-gtk-linux-x86_64.zip` repository and how  do I install older alternate versions or nightly builds and snapshots.
the file list of all of it's versions should be on the internet right? they're always like this.

**Comment by parg** [comment] 2022-01-22 12:56
Latest releases:

    https://download.eclipse.org/eclipse/downloads/index.html#Latest_Release

Archived:

    https://archive.eclipse.org/eclipse/downloads/

The mapping from release (e.g. 4.20) to version number (4.20 -> 4944r26) is not obvious, you have to download the SWT .zip, extract the swt.jar from it and then look in the swt.jar for the DLL names that include the version number.

**Comment by davidalb97** [comment] 2022-02-24 13:29
Another alternative are the maven releases:
```
https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.swt.gtk.linux.x86_64
```
| mvn package version | version.txt |
|:-------------------:|:-----------:|
|       3.118.0       |    4.948    |
|       3.117.0       |    4.946    |
|      3.116.100      |    4.944    |
|       3.116.0       |    4.942    |
|      3.115.100      |    4.940    |
|       3.115.0       |    4.936    |
|      3.114.100      |    4.934    |
|       3.114.0       |    4.924    |
|       3.113.0       |    4.924    |
|       3.112.0       |    4.924    |
|       3.111.0       |    4.924    |
|       3.110.0       |    4.924    |
|       3.109.0       |    4.922    |
|       3.108.0       |    4.919    |
|       3.107.0       |    4.880    |
|       3.106.3       |    4.763    |
|       3.106.2       |    4.763    |
|       3.106.1       |    4.758    |
|       3.106.0       |    4.757    |
|       3.105.3       |    4.629    |
|       3.105.2       |    4.628    |

Note: From Versions 3.109.0 (4.922) and older, the UI starts to break, also note that BiglyBT will force you to update swt lib to 3.116.0 (4.942) automatically if you try those older versions.
On my case the older swt lib jar at "/opt/biblybt/swt/swt-x86_64.jar"
was replaced by "/opt/biblybt/swt/swt.jar" during the update.

**Comment by mohsentux** [comment] 2022-04-07 21:56
I'm happy to announce, after waiting so long, the situation is resolved. I no longer have any problems with the newer version of the app.
I propose closing this issue

**Comment by davidalb97** [comment] 2022-04-08 21:40
Did you do anything new to solve it other than just updating?

**Comment by mohsentux** [comment] 2022-04-08 21:42
All I did was an update. that's all

**Comment by Nik343** [comment] 2022-12-05 07:10
I've been having issues with SWT on linux for well over half a year now. I found that the BiglyBT console ui works great to an extent but the overall capability of both cli and the Web Remote plugin is fairly weak.
Today I discovered an untraditional way of getting around this issue by running Bigly in Wine, as this allows me to use it without freezes or crashes, and I can also use linux for everything else on the machine, like ZFS for example. Are there any immediate downsides to this solution?

**Comment by davidalb97** [comment] 2022-12-05 22:06
> I've been having issues with SWT on linux for well over half a year now. I found that the BiglyBT console ui works great to an extent but the overall capability of both cli and the Web Remote plugin is fairly weak. Today I discovered an untraditional way of getting around this issue by running Bigly in Wine, as this allows me to use it without freezes or crashes, and I can also use linux for everything else on the machine, like ZFS for example. Are there any immediate downsides to this solution?

I don't think there are any problems when emulating, there is however, a performance impact.

I found out that I could avoid KDE from freezing when not opening the Application Drawer from the Panel (taskbar).
Not having erroring torrents (archiving when missing files) also helped from freezing until the Application Drawer was opened, allowing me to use the KDE Panel (as long as no Application Drawers of any kind were opened).

**Closed** 2024-01-13 11:50 UTC
