### ISSUE TITLE
Set port fails to open?

### ISSUE THREAD

**Issue by Jirnkuu** [BiglySoftware/BiglyBT#2716] opened 2022-09-15 05:54 UTC
Hello
I set a port in the settings of BiglyBT, both TCP and UDP, I then accessed my router settings and opened said port, made sure to apply my device's ipv4 address to the port, both in TCP and UDP, the problem is that the ports do not actually get open, and I am not sure why, when I run the TCP listen port test I get a NAT error, connection timed out. the UDP test is also timed out.

Is there a way to solve the issue?

my bigly version is B3.1.0.0/4 az3
my windows is 10 v10.0

**Comment by Jirnkuu** [comment] 2022-09-15 14:37
I only have the windows defender. but I made sure to exclude biglybt, it used to work before. I'm not sure why it doesn't now.

**Comment by parg** [comment] 2022-09-15 14:45
Dunno, reboot everything.

**Comment by Jirnkuu** [comment] 2022-09-15 15:36
I tried. doesn't work. I rebooted my pc & bigly, also deleted and re-applied the ports in my router settings. did not work. I guess I'll try to shut off and on my router itself. and contant my isp.

**Comment by Pendaws** [comment] 2022-09-17 05:11
Hi there Jirnkuu;
I had a similar problem and found that there is a setting in Tools/Options/Advanced Network settings/ that might be the cause.
A setting marked "Bind to local IP address or interface" Mine had a setting of Net6. I removed it, saved the setting and tried again to download and voila, it worked. 
Just remember the setting you have in that line and remove it, save and restart Bigly BT and I hope that it is the problem and that the small fix is instant :)

**Comment by Jirnkuu** [comment] 2022-09-19 20:50
@Pendaws Hi, I checked, that setting is empty for me. no address written to that setting.

**Comment by Jirnkuu** [comment] 2022-09-19 20:54
@parg  Hi Parg, do I need a static IP in order to port forward? 
the IPv4 address of my device is set with a fixed address, that is the same address I put on my router when I opened the ports.
but when I contacted my ISP they told me static IP service costs a monthly fee, so I'm not quite sure what the difference is.

**Comment by parg** [comment] 2022-09-19 21:13
No, you don't need a static IP. 

When you don't have a static IP the ISP still allocates you a public IP address, it just has the potential to change. I don't have a static IP for me the public IP they allocate me only tends to change when I reboot by router.

Port forwarding for a port (say 1234 to your internal IP, say 192.168.1.23, on the same port)) means that given your current IP (say 200.10.20.30) someone on the internet that connects to 200.10.20.30:1234 will have that connection end up at 192.168.1.23:1234

So if it isn't working then the connection to 200.10.20.30:1234 is failing to get through either because

1) your router isn't forwarding to 192.168.1.23
2) the connection is getting to 192.168.1.23 but something on that machine (AV, firewall) isn't passing the connection to BiglyBT
3) you're using a VPN that you haven't mentioned
4) fuck knows

**Comment by Jirnkuu** [comment] 2022-09-19 21:29
Does it matter what port do I choose for Bigly? I picked something between the 49160–65534 range.
The only firewall/AV I have is windows defender, I made sure to give bigly.exe a pass on it.
I am not using a VPN.

so sadly this is a "4." situation.

**Comment by parg** [comment] 2022-09-20 06:59
That port range is fine

**Comment by libellula** [comment] 2022-10-16 19:38
Here's my settings on my modem, and the IP address is static.
![screenshot](https://user-images.githubusercontent.com/61087558/196054630-7257719f-fa6c-4ebe-baf7-0af7973ef623.jpg)

**Comment by parg** [comment] 2022-10-17 08:01
As long as you have

![image](https://user-images.githubusercontent.com/395293/196121550-83aea100-ede3-4298-967d-620543a022a6.png)

and your computer's firewall/antivirus is allowing incoming connections to BiglyBT.exe (assuming Windows) then things should work (assuming you're not using a VPN)

**Comment by libellula** [comment] 2022-10-17 08:52
> As long as you have
> 
> ![image](https://user-images.githubusercontent.com/395293/196121550-83aea100-ede3-4298-967d-620543a022a6.png)
> 
> and your computer's firewall/antivirus is allowing incoming connections to BiglyBT.exe (assuming Windows) then things should work (assuming you're not using a VPN)

Exactly.

**Comment by parg** [comment] 2022-10-17 08:59
What is the result of performing a NAT test via the Help menu's "NAT/Firewall Test" ?

**Comment by libellula** [comment] 2022-10-17 09:26
> What is the result of performing a NAT test via the Help menu's "NAT/Firewall Test" ?

Ok.

**Comment by SodaWithoutSparkles** [comment] 2023-04-08 18:22
I have the same behaviour. The strange thing is, I can telnet to that port and it said connected, even if I am on mobile data. I used port 60000.

```
$ telnet <publicIP> 60000

Connected to <publicIP>.
Escape character is '^]'.
```

The network diagnostic still said TCP inbound 60000 not available. UDP was fine. 

```
Test failed: NAT test failed: Connection to <publicIP>:60000 (your computer) refused
Check your port forwarding for TCP 60000
```

I have port forwarded on my router. UDP inbound work reguardless of wether port forwarding was enabled or not. I have i2pd, a public-facing web server and a working self-hosted VPN installed, so my ISP is not likely to cause problems.

**Closed** 2024-01-13 11:49 UTC
