### ISSUE TITLE
Starts and freezes on Ubuntu 17.04

### ISSUE THREAD

**Issue by thwaller** [BiglySoftware/BiglyBT#6] opened 2017-08-04 21:48 UTC
After install, the application will start, then enters a not responding state. I used the installer from the website here: https://files.biglybt.com/installer/BiglyBT_Installer.sh

The installer starts by saying:
1) don't need JNA
2) not wayland

At this point, I use all the defaulted options and install. The install completes, then I run BiglyBT. At that point, the GUI appears and never becomes responsive. All I can do is force quit.

I have not looked into this further, but I did try to reinstall it. Just wanted to post in the case that others may be having a similar issue.

**Comment by TuxPaper** [comment] 2017-08-05 00:25
Which desktop environment are you using?  I've tested Ubuntu 17.04 with Unity desktop environment in the past and it seemed to work, but I can check again.

**Comment by thwaller** [comment] 2017-08-05 01:13
I am currently using MATE:
Release 17.04 (Zesty Zapus) 64-bit
Kernel Linux 4.10.0-29-generic x86_64
MATE 1.18.0

**Comment by csylvain** [comment] 2017-08-05 01:53
same issue for me: SuSE Leap 42.2  Java 1.8.0_144 (Oracle)

starting biglybt from shell:
[Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.]
DEBUG::Fri Aug 04 21:48:48 EDT 2017::com.biglybt.core.util.DebugLight::printStackTrace::35:
  java.lang.NullPointerException
        at com.biglybt.core.networkmanager.NetworkManager.getConnections(NetworkManager.java:542)
        at com.biglybt.core.networkmanager.admin.impl.NetworkAdminImpl.checkConnectionRoutes(NetworkAdminImpl.java:2918)
        at com.biglybt.core.networkmanager.admin.impl.NetworkAdminImpl$6.perform(NetworkAdminImpl.java:241)
        at com.biglybt.core.util.TimerEventPeriodic.perform(TimerEventPeriodic.java:104)
        at com.biglybt.core.util.TimerEvent.runSupport(TimerEvent.java:133)
        at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
        at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:328)
        at com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:720)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:295)

**Comment by TuxPaper** [comment] 2017-08-05 03:26
hmm, MATE worked for me, @thwaller 
![image](https://user-images.githubusercontent.com/725353/28992506-0dac65da-7953-11e7-9274-784f7bbac8c5.png)

Try running it from terminal, like csylvain did and see what the last bit of spew is before it stalls

**Comment by thwaller** [comment] 2017-08-05 06:09
I received a ton of items, but here is the last portion of it:

(BiglyBT:11436): GLib-CRITICAL **: g_base64_encode_step: assertion 'in != NULL' failed

(BiglyBT:11436): GLib-CRITICAL **: g_base64_encode_step: assertion 'in != NULL' failed
UIFunctions/ImageLoad took 34ms
new shell took 364ms
new shell setup took 126ms
skin init took 264ms
MainMenu init took 307ms
pre skin widgets init took 180ms
skin widgets (1/2) init took 691ms
skin widgets (2/2) init took 415ms
pre SWTInstance init took 0ms
Init Core Columns took 226ms
SWTInstance init took 4ms

(BiglyBT:11436): Gtk-WARNING **: Allocating size to GtkBox 0x7fa1587b7150 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(BiglyBT:11436): Gtk-WARNING **: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
shell.layout took 191ms
---------SHOWN AT 1501913235720;8353ms
---------DONE DISPATCH AT 1501913236256;8886ms
Prism-ES2 Error : GL_VERSION (major.minor) = 1.4
[Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.]
[Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.]
[Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.]
[Successfully loaded]
[Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.]
[Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.]
[Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.]
DEBUG::Sat Aug 05 01:08:06 CDT 2017::com.biglybt.core.util.DebugLight::printStackTrace::35:
  java.lang.NullPointerException
	at com.biglybt.core.networkmanager.NetworkManager.getConnections(NetworkManager.java:542)
	at com.biglybt.core.networkmanager.admin.impl.NetworkAdminImpl.checkConnectionRoutes(NetworkAdminImpl.java:2918)
	at com.biglybt.core.networkmanager.admin.impl.NetworkAdminImpl$6.perform(NetworkAdminImpl.java:241)
	at com.biglybt.core.util.TimerEventPeriodic.perform(TimerEventPeriodic.java:104)
	at com.biglybt.core.util.TimerEvent.runSupport(TimerEvent.java:133)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:328)
	at com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:720)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:295)

**Comment by TuxPaper** [comment] 2017-08-05 07:19
Well, I guess both of you having the same error is a 'good' thing.  @thwaller are you also using Oracle/Sun Java, or is it OpenJDK?

The JavaFX runLater() line is suspicious to me, because we don't use JavaFX at all.  I'll poke around and see if I can reproduce it somehow.  The NullPointerException seems to be a symptom of the core not being started yet, and not the cause of the problem (The problem being, the core isn't started..)

If you want to try console mode, you can run `./biglybt -ui console` and this should start up BiglyBT within your terminal, with some basic console commands.  From there you can try to start the UI with `ui swt`

**Comment by TuxPaper** [comment] 2017-08-05 07:23
Oh, I might know where the JavaFX is coming from.
remove `~/biglybt/dorkbox-systemtray.jar` and see if that improves anything.  It should at least get rid of the JavaFX warning.

And you can ignore any of the lines that start with "(SWT:" .. that's just the SWT library doing things the wrong way (they don't affect things)

**Comment by thwaller** [comment] 2017-08-05 07:36
> @thwaller are you also using Oracle/Sun Java, or is it OpenJDK?

I have options to configure both OpenJDK Java 8 and Oracle Java 8. How might I find which is being used?

> remove ~/biglybt/dorkbox-systemtray.jar and see if that improves anything. 

Wow, that UI I see is very much different, and did not lock up.

**Comment by TuxPaper** [comment] 2017-08-05 07:49
I believe `java -version` has "OpenJDK" in it, and Sun/Oracle doesn't.

But that doesn't matter now, since you got it to launch!

I'll either remove dorkbox or try to remove the JavaFX from it.  Thanks for working through this with me.

**Comment by thwaller** [comment] 2017-08-05 07:52
> I believe java -version has "OpenJDK" in it, and Sun/Oracle doesn't.

For the sake of debugging and completeness, here is the result:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by csylvain** [comment] 2017-08-05 20:57
I can confirm: startup "freeze" gone after renaming the dorkbox jar file.

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by TuxPaper** [comment] 2017-08-07 18:19
Closing Issue.

I've updated dorkbox and removed any JavaFX usage.  Dorkbox is used only on a small percentage of linux desktops (specifically, one's that use AppIndicator library for their status bar), and can be safely deleted for most *nix users.

**Closed by TuxPaper** 2017-08-07 18:19 UTC

**Comment by acerspyro** [comment] 2021-07-18 23:13
Issue is still present on Fedora 34 with OpenJDK, fix still works.
